services:
  - type: web
    name: go-chat-api
    runtime: docker
    region: singapore
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /healthz
    envVars:
      - key: GOCHAT_POSTGRES_URL
        sync: false
      - key: GOCHAT_REDIS_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: GOCHAT_S3_ENDPOINT
        sync: false
      - key: GOCHAT_S3_BUCKET
        sync: false
      - key: GOCHAT_S3_ACCESS_KEY_ID
        sync: false
      - key: GOCHAT_S3_SECRET_ACCESS_KEY
        sync: false
      - key: GOCHAT_S3_REGION
        sync: false
