services:
  - type: web
    name: go-chat-api
    runtime: docker
    region: singapore
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/v1/health
    preDeployCommand: ./migrate
    envVars:
      - key: GOCHAT_POSTGRES_URL
        fromDatabase:
          name: go-chat-postgres
          property: connectionString
      - key: GOCHAT_REDIS_URL
        fromService:
          type: keyvalue
          name: go-chat-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: GOCHAT_S3_ENDPOINT
        sync: false
      - key: GOCHAT_S3_BUCKET
        sync: false
      - key: GOCHAT_S3_ACCESS_KEY_ID
        sync: false
      - key: GOCHAT_S3_SECRET_ACCESS_KEY
        sync: false
      - key: GOCHAT_S3_REGION
        sync: false
  - type: keyvalue
    name: go-chat-redis
    region: singapore
    plan: starter
    maxmemoryPolicy: noeviction
    ipAllowList: []

databases:
  - name: go-chat-postgres
    region: singapore
    plan: basic-256mb
    databaseName: gochat
    user: gochat
    ipAllowList: []
