// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: core.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMediaMessage = `-- name: AddMediaMessage :one
INSERT INTO messages (id,session_id,sender_id,client_operation_id,cursor,kind,body,expires_at) SELECT $1,$2,$3,$4,$5,'media','',CASE cs.retention_policy WHEN '24h' THEN now()+interval '24 hours' WHEN '7d' THEN now()+interval '7 days' WHEN '30d' THEN now()+interval '30 days' ELSE NULL END FROM chat_sessions cs WHERE cs.id=$2 ON CONFLICT(sender_id,client_operation_id) DO UPDATE SET body=messages.body RETURNING id,session_id,sender_id,client_operation_id,cursor,kind,body,state,created_at,edited_at,deleted_at,expires_at,false
`

type AddMediaMessageParams struct {
	ID                string `json:"id"`
	SessionID         string `json:"session_id"`
	SenderID          string `json:"sender_id"`
	ClientOperationID string `json:"client_operation_id"`
	Cursor            int64  `json:"cursor"`
}

type AddMediaMessageRow struct {
	ID                string             `json:"id"`
	SessionID         string             `json:"session_id"`
	SenderID          string             `json:"sender_id"`
	ClientOperationID string             `json:"client_operation_id"`
	Cursor            int64              `json:"cursor"`
	Kind              string             `json:"kind"`
	Body              pgtype.Text        `json:"body"`
	State             string             `json:"state"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	EditedAt          pgtype.Timestamptz `json:"edited_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	Column13          bool               `json:"column_13"`
}

func (q *Queries) AddMediaMessage(ctx context.Context, arg AddMediaMessageParams) (AddMediaMessageRow, error) {
	row := q.db.QueryRow(ctx, addMediaMessage,
		arg.ID,
		arg.SessionID,
		arg.SenderID,
		arg.ClientOperationID,
		arg.Cursor,
	)
	var i AddMediaMessageRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.SenderID,
		&i.ClientOperationID,
		&i.Cursor,
		&i.Kind,
		&i.Body,
		&i.State,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
		&i.ExpiresAt,
		&i.Column13,
	)
	return i, err
}

const addParticipant = `-- name: AddParticipant :exec
INSERT INTO session_participants (session_id,user_id) VALUES ($1,$2) ON CONFLICT DO NOTHING
`

type AddParticipantParams struct {
	SessionID string `json:"session_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) AddParticipant(ctx context.Context, arg AddParticipantParams) error {
	_, err := q.db.Exec(ctx, addParticipant, arg.SessionID, arg.UserID)
	return err
}

const archiveSession = `-- name: ArchiveSession :exec
UPDATE session_participants SET archived_at=now() WHERE session_id=$1 AND user_id=$2 AND archived_at IS NULL
`

type ArchiveSessionParams struct {
	SessionID string `json:"session_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) ArchiveSession(ctx context.Context, arg ArchiveSessionParams) error {
	_, err := q.db.Exec(ctx, archiveSession, arg.SessionID, arg.UserID)
	return err
}

const clearOwnProfileAvatar = `-- name: ClearOwnProfileAvatar :one
UPDATE anonymous_profiles SET avatar_storage_key=NULL, updated_at=now() WHERE user_id=$1 RETURNING user_id,username,username_normalized,avatar_storage_key,status_message
`

type ClearOwnProfileAvatarRow struct {
	UserID             string      `json:"user_id"`
	Username           string      `json:"username"`
	UsernameNormalized string      `json:"username_normalized"`
	AvatarStorageKey   pgtype.Text `json:"avatar_storage_key"`
	StatusMessage      string      `json:"status_message"`
}

func (q *Queries) ClearOwnProfileAvatar(ctx context.Context, userID string) (ClearOwnProfileAvatarRow, error) {
	row := q.db.QueryRow(ctx, clearOwnProfileAvatar, userID)
	var i ClearOwnProfileAvatarRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.UsernameNormalized,
		&i.AvatarStorageKey,
		&i.StatusMessage,
	)
	return i, err
}

const completeOnboardingCheckpoint = `-- name: CompleteOnboardingCheckpoint :exec
UPDATE onboarding_checkpoints SET step='complete',candidate_username=$1,updated_at=now() WHERE user_id=$2
`

type CompleteOnboardingCheckpointParams struct {
	CandidateUsername pgtype.Text `json:"candidate_username"`
	UserID            string      `json:"user_id"`
}

func (q *Queries) CompleteOnboardingCheckpoint(ctx context.Context, arg CompleteOnboardingCheckpointParams) error {
	_, err := q.db.Exec(ctx, completeOnboardingCheckpoint, arg.CandidateUsername, arg.UserID)
	return err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (id,username,username_normalized,email,password_hash,linked_user_id,last_signed_in_at) VALUES ($1,$2,$3,$4,$5,$6,now()) RETURNING id,username,username_normalized,email,password_hash,linked_user_id,status,email_verified_at,last_signed_in_at,created_at,updated_at
`

type CreateAccountParams struct {
	ID                 string      `json:"id"`
	Username           string      `json:"username"`
	UsernameNormalized string      `json:"username_normalized"`
	Email              string      `json:"email"`
	PasswordHash       string      `json:"password_hash"`
	LinkedUserID       pgtype.Text `json:"linked_user_id"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.Username,
		arg.UsernameNormalized,
		arg.Email,
		arg.PasswordHash,
		arg.LinkedUserID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UsernameNormalized,
		&i.Email,
		&i.PasswordHash,
		&i.LinkedUserID,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastSignedInAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAccountSession = `-- name: CreateAccountSession :exec
INSERT INTO account_sessions (id,account_id,token_hash,expires_at) VALUES ($1,$2,$3,now()+interval '30 days')
`

type CreateAccountSessionParams struct {
	ID        string `json:"id"`
	AccountID string `json:"account_id"`
	TokenHash string `json:"token_hash"`
}

func (q *Queries) CreateAccountSession(ctx context.Context, arg CreateAccountSessionParams) error {
	_, err := q.db.Exec(ctx, createAccountSession, arg.ID, arg.AccountID, arg.TokenHash)
	return err
}

const createBlock = `-- name: CreateBlock :exec
INSERT INTO blocked_users (blocker_id,blocked_user_id) VALUES ($1,$2) ON CONFLICT DO NOTHING
`

type CreateBlockParams struct {
	BlockerID     string `json:"blocker_id"`
	BlockedUserID string `json:"blocked_user_id"`
}

func (q *Queries) CreateBlock(ctx context.Context, arg CreateBlockParams) error {
	_, err := q.db.Exec(ctx, createBlock, arg.BlockerID, arg.BlockedUserID)
	return err
}

const createBrowserSession = `-- name: CreateBrowserSession :exec
INSERT INTO browser_sessions (id,user_id,token_hash,csrf_hash,expires_at) VALUES ($1,$2,$3,$4,now()+interval '30 days')
`

type CreateBrowserSessionParams struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	TokenHash string `json:"token_hash"`
	CsrfHash  string `json:"csrf_hash"`
}

func (q *Queries) CreateBrowserSession(ctx context.Context, arg CreateBrowserSessionParams) error {
	_, err := q.db.Exec(ctx, createBrowserSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.CsrfHash,
	)
	return err
}

const createDataDeletionRequest = `-- name: CreateDataDeletionRequest :one
INSERT INTO data_rights_requests (id,user_id,request_kind,reference_code) VALUES ($1,$2,'deletion',$3) ON CONFLICT DO NOTHING RETURNING id,request_kind,status,reference_code,confirmed_at,created_at,updated_at
`

type CreateDataDeletionRequestParams struct {
	ID            string `json:"id"`
	UserID        string `json:"user_id"`
	ReferenceCode string `json:"reference_code"`
}

type CreateDataDeletionRequestRow struct {
	ID            string             `json:"id"`
	RequestKind   string             `json:"request_kind"`
	Status        string             `json:"status"`
	ReferenceCode string             `json:"reference_code"`
	ConfirmedAt   pgtype.Timestamptz `json:"confirmed_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateDataDeletionRequest(ctx context.Context, arg CreateDataDeletionRequestParams) (CreateDataDeletionRequestRow, error) {
	row := q.db.QueryRow(ctx, createDataDeletionRequest, arg.ID, arg.UserID, arg.ReferenceCode)
	var i CreateDataDeletionRequestRow
	err := row.Scan(
		&i.ID,
		&i.RequestKind,
		&i.Status,
		&i.ReferenceCode,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDirectSession = `-- name: CreateDirectSession :one
INSERT INTO chat_sessions (id,direct_pair_key) VALUES ($1,$2) ON CONFLICT(direct_pair_key) DO UPDATE SET last_activity_at=chat_sessions.last_activity_at RETURNING id,direct_pair_key,status,last_activity_at,created_at
`

type CreateDirectSessionParams struct {
	ID            string `json:"id"`
	DirectPairKey string `json:"direct_pair_key"`
}

type CreateDirectSessionRow struct {
	ID             string             `json:"id"`
	DirectPairKey  string             `json:"direct_pair_key"`
	Status         string             `json:"status"`
	LastActivityAt pgtype.Timestamptz `json:"last_activity_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateDirectSession(ctx context.Context, arg CreateDirectSessionParams) (CreateDirectSessionRow, error) {
	row := q.db.QueryRow(ctx, createDirectSession, arg.ID, arg.DirectPairKey)
	var i CreateDirectSessionRow
	err := row.Scan(
		&i.ID,
		&i.DirectPairKey,
		&i.Status,
		&i.LastActivityAt,
		&i.CreatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (id,session_id,sender_id,client_operation_id,cursor,kind,body,expires_at) SELECT $1,$2,$3,$4,$5,$6,$7,CASE cs.retention_policy WHEN '24h' THEN now()+interval '24 hours' WHEN '7d' THEN now()+interval '7 days' WHEN '30d' THEN now()+interval '30 days' ELSE NULL END FROM chat_sessions cs WHERE cs.id=$2 ON CONFLICT(sender_id,client_operation_id) DO UPDATE SET body=messages.body RETURNING id,session_id,sender_id,client_operation_id,cursor,kind,body,state,created_at,expires_at
`

type CreateMessageParams struct {
	ID                string      `json:"id"`
	SessionID         string      `json:"session_id"`
	SenderID          string      `json:"sender_id"`
	ClientOperationID string      `json:"client_operation_id"`
	Cursor            int64       `json:"cursor"`
	Kind              string      `json:"kind"`
	Body              pgtype.Text `json:"body"`
}

type CreateMessageRow struct {
	ID                string             `json:"id"`
	SessionID         string             `json:"session_id"`
	SenderID          string             `json:"sender_id"`
	ClientOperationID string             `json:"client_operation_id"`
	Cursor            int64              `json:"cursor"`
	Kind              string             `json:"kind"`
	Body              pgtype.Text        `json:"body"`
	State             string             `json:"state"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (CreateMessageRow, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.SessionID,
		arg.SenderID,
		arg.ClientOperationID,
		arg.Cursor,
		arg.Kind,
		arg.Body,
	)
	var i CreateMessageRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.SenderID,
		&i.ClientOperationID,
		&i.Cursor,
		&i.Kind,
		&i.Body,
		&i.State,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createMessageRequest = `-- name: CreateMessageRequest :one
INSERT INTO message_requests (id,sender_user_id,recipient_user_id) VALUES ($1,$2,$3) ON CONFLICT(sender_user_id,recipient_user_id) DO UPDATE SET status='pending',resolved_at=NULL,created_at=now() WHERE message_requests.status IN ('declined','blocked') RETURNING id,sender_user_id,recipient_user_id,status,created_at,resolved_at
`

type CreateMessageRequestParams struct {
	ID              string `json:"id"`
	SenderUserID    string `json:"sender_user_id"`
	RecipientUserID string `json:"recipient_user_id"`
}

func (q *Queries) CreateMessageRequest(ctx context.Context, arg CreateMessageRequestParams) (MessageRequest, error) {
	row := q.db.QueryRow(ctx, createMessageRequest, arg.ID, arg.SenderUserID, arg.RecipientUserID)
	var i MessageRequest
	err := row.Scan(
		&i.ID,
		&i.SenderUserID,
		&i.RecipientUserID,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const createProfile = `-- name: CreateProfile :one
INSERT INTO anonymous_profiles (user_id, username, username_normalized, identity_seed) VALUES ($1,$2,$3,$4) RETURNING user_id, username, username_normalized
`

type CreateProfileParams struct {
	UserID             string `json:"user_id"`
	Username           string `json:"username"`
	UsernameNormalized string `json:"username_normalized"`
	IdentitySeed       string `json:"identity_seed"`
}

type CreateProfileRow struct {
	UserID             string `json:"user_id"`
	Username           string `json:"username"`
	UsernameNormalized string `json:"username_normalized"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (CreateProfileRow, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.UserID,
		arg.Username,
		arg.UsernameNormalized,
		arg.IdentitySeed,
	)
	var i CreateProfileRow
	err := row.Scan(&i.UserID, &i.Username, &i.UsernameNormalized)
	return i, err
}

const createReport = `-- name: CreateReport :exec
INSERT INTO reports (id,reporter_id,reported_user_id,session_id,reason) VALUES ($1,$2,$3,$4,$5)
`

type CreateReportParams struct {
	ID             string `json:"id"`
	ReporterID     string `json:"reporter_id"`
	ReportedUserID string `json:"reported_user_id"`
	SessionID      string `json:"session_id"`
	Reason         string `json:"reason"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) error {
	_, err := q.db.Exec(ctx, createReport,
		arg.ID,
		arg.ReporterID,
		arg.ReportedUserID,
		arg.SessionID,
		arg.Reason,
	)
	return err
}

const createReportReceipt = `-- name: CreateReportReceipt :one
INSERT INTO reports (id,reporter_id,reported_user_id,session_id,reason,reference_code) VALUES ($1,$2,$3,$4,$5,$6) RETURNING id,reference_code,status,created_at
`

type CreateReportReceiptParams struct {
	ID             string `json:"id"`
	ReporterID     string `json:"reporter_id"`
	ReportedUserID string `json:"reported_user_id"`
	SessionID      string `json:"session_id"`
	Reason         string `json:"reason"`
	ReferenceCode  string `json:"reference_code"`
}

type CreateReportReceiptRow struct {
	ID            string             `json:"id"`
	ReferenceCode string             `json:"reference_code"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateReportReceipt(ctx context.Context, arg CreateReportReceiptParams) (CreateReportReceiptRow, error) {
	row := q.db.QueryRow(ctx, createReportReceipt,
		arg.ID,
		arg.ReporterID,
		arg.ReportedUserID,
		arg.SessionID,
		arg.Reason,
		arg.ReferenceCode,
	)
	var i CreateReportReceiptRow
	err := row.Scan(
		&i.ID,
		&i.ReferenceCode,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createRetentionEvent = `-- name: CreateRetentionEvent :exec
INSERT INTO retention_events (id,session_id,actor_user_id,previous_policy,next_policy) VALUES ($1,$2,$3,$4,$5)
`

type CreateRetentionEventParams struct {
	ID             string `json:"id"`
	SessionID      string `json:"session_id"`
	ActorUserID    string `json:"actor_user_id"`
	PreviousPolicy string `json:"previous_policy"`
	NextPolicy     string `json:"next_policy"`
}

func (q *Queries) CreateRetentionEvent(ctx context.Context, arg CreateRetentionEventParams) error {
	_, err := q.db.Exec(ctx, createRetentionEvent,
		arg.ID,
		arg.SessionID,
		arg.ActorUserID,
		arg.PreviousPolicy,
		arg.NextPolicy,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id) VALUES ($1) RETURNING id, status, created_at, updated_at
`

func (q *Queries) CreateUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserSettings = `-- name: CreateUserSettings :exec
INSERT INTO user_settings (user_id) VALUES ($1)
`

func (q *Queries) CreateUserSettings(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, createUserSettings, userID)
	return err
}

const deleteMediaAsset = `-- name: DeleteMediaAsset :exec
DELETE FROM media_assets WHERE id=$1
`

func (q *Queries) DeleteMediaAsset(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteMediaAsset, id)
	return err
}

const deleteMessage = `-- name: DeleteMessage :one
UPDATE messages SET body=NULL, state='deleted', deleted_at=now() WHERE id=$1 AND session_id=$2 AND sender_id=$3 AND deleted_at IS NULL RETURNING id
`

type DeleteMessageParams struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	SenderID  string `json:"sender_id"`
}

func (q *Queries) DeleteMessage(ctx context.Context, arg DeleteMessageParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteMessage, arg.ID, arg.SessionID, arg.SenderID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const expireDueMessages = `-- name: ExpireDueMessages :many
UPDATE messages SET body=NULL,state='expired',deleted_at=now(),expired_at=now() WHERE expires_at<=now() AND deleted_at IS NULL AND NOT EXISTS (SELECT 1 FROM media_assets ma WHERE ma.message_id=messages.id) RETURNING id,session_id
`

type ExpireDueMessagesRow struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
}

func (q *Queries) ExpireDueMessages(ctx context.Context) ([]ExpireDueMessagesRow, error) {
	rows, err := q.db.Query(ctx, expireDueMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpireDueMessagesRow{}
	for rows.Next() {
		var i ExpireDueMessagesRow
		if err := rows.Scan(&i.ID, &i.SessionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id,username,username_normalized,email,password_hash,linked_user_id,status,email_verified_at,last_signed_in_at,created_at,updated_at FROM accounts WHERE id=$1
`

func (q *Queries) GetAccountByID(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UsernameNormalized,
		&i.Email,
		&i.PasswordHash,
		&i.LinkedUserID,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastSignedInAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByIdentifier = `-- name: GetAccountByIdentifier :one
SELECT id,username,username_normalized,email,password_hash,linked_user_id,status,email_verified_at,last_signed_in_at,created_at,updated_at FROM accounts WHERE username_normalized=$1 OR lower(email)=lower($1)
`

func (q *Queries) GetAccountByIdentifier(ctx context.Context, usernameNormalized string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByIdentifier, usernameNormalized)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UsernameNormalized,
		&i.Email,
		&i.PasswordHash,
		&i.LinkedUserID,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastSignedInAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountForUser = `-- name: GetAccountForUser :one
SELECT id,username,username_normalized,email,password_hash,linked_user_id,status,email_verified_at,last_signed_in_at,created_at,updated_at FROM accounts WHERE linked_user_id=$1
`

func (q *Queries) GetAccountForUser(ctx context.Context, linkedUserID pgtype.Text) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountForUser, linkedUserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.UsernameNormalized,
		&i.Email,
		&i.PasswordHash,
		&i.LinkedUserID,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastSignedInAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountSession = `-- name: GetAccountSession :one
SELECT account_id FROM account_sessions WHERE token_hash=$1 AND revoked_at IS NULL AND expires_at>now()
`

func (q *Queries) GetAccountSession(ctx context.Context, tokenHash string) (string, error) {
	row := q.db.QueryRow(ctx, getAccountSession, tokenHash)
	var account_id string
	err := row.Scan(&account_id)
	return account_id, err
}

const getBrowserSessionUser = `-- name: GetBrowserSessionUser :one
SELECT user_id FROM browser_sessions WHERE token_hash=$1 AND revoked_at IS NULL AND expires_at>now()
`

func (q *Queries) GetBrowserSessionUser(ctx context.Context, tokenHash string) (string, error) {
	row := q.db.QueryRow(ctx, getBrowserSessionUser, tokenHash)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const getDirectSessionByPair = `-- name: GetDirectSessionByPair :one
SELECT id,direct_pair_key,status,last_activity_at,created_at FROM chat_sessions WHERE direct_pair_key=$1
`

type GetDirectSessionByPairRow struct {
	ID             string             `json:"id"`
	DirectPairKey  string             `json:"direct_pair_key"`
	Status         string             `json:"status"`
	LastActivityAt pgtype.Timestamptz `json:"last_activity_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetDirectSessionByPair(ctx context.Context, directPairKey string) (GetDirectSessionByPairRow, error) {
	row := q.db.QueryRow(ctx, getDirectSessionByPair, directPairKey)
	var i GetDirectSessionByPairRow
	err := row.Scan(
		&i.ID,
		&i.DirectPairKey,
		&i.Status,
		&i.LastActivityAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMediaMessageByOperation = `-- name: GetMediaMessageByOperation :one
SELECT m.id,m.session_id,m.sender_id,m.client_operation_id,m.cursor,m.kind,COALESCE(m.body,''),m.state,m.created_at,m.edited_at,m.deleted_at,m.expires_at,ma.storage_key,ma.file_name,ma.content_type,ma.byte_size
FROM messages m
JOIN media_assets ma ON ma.message_id=m.id
WHERE m.sender_id=$1 AND m.client_operation_id=$2 AND m.kind='media'
`

type GetMediaMessageByOperationParams struct {
	SenderID          string `json:"sender_id"`
	ClientOperationID string `json:"client_operation_id"`
}

type GetMediaMessageByOperationRow struct {
	ID                string             `json:"id"`
	SessionID         string             `json:"session_id"`
	SenderID          string             `json:"sender_id"`
	ClientOperationID string             `json:"client_operation_id"`
	Cursor            int64              `json:"cursor"`
	Kind              string             `json:"kind"`
	Body              string             `json:"body"`
	State             string             `json:"state"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	EditedAt          pgtype.Timestamptz `json:"edited_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	StorageKey        string             `json:"storage_key"`
	FileName          string             `json:"file_name"`
	ContentType       string             `json:"content_type"`
	ByteSize          int64              `json:"byte_size"`
}

func (q *Queries) GetMediaMessageByOperation(ctx context.Context, arg GetMediaMessageByOperationParams) (GetMediaMessageByOperationRow, error) {
	row := q.db.QueryRow(ctx, getMediaMessageByOperation, arg.SenderID, arg.ClientOperationID)
	var i GetMediaMessageByOperationRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.SenderID,
		&i.ClientOperationID,
		&i.Cursor,
		&i.Kind,
		&i.Body,
		&i.State,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
		&i.ExpiresAt,
		&i.StorageKey,
		&i.FileName,
		&i.ContentType,
		&i.ByteSize,
	)
	return i, err
}

const getMessageCursor = `-- name: GetMessageCursor :one
SELECT cursor FROM messages WHERE id=$1 AND session_id=$2
`

type GetMessageCursorParams struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
}

func (q *Queries) GetMessageCursor(ctx context.Context, arg GetMessageCursorParams) (int64, error) {
	row := q.db.QueryRow(ctx, getMessageCursor, arg.ID, arg.SessionID)
	var cursor int64
	err := row.Scan(&cursor)
	return cursor, err
}

const getMessageRequestBetween = `-- name: GetMessageRequestBetween :one
SELECT id,sender_user_id,recipient_user_id,status,created_at,resolved_at
FROM message_requests
WHERE (sender_user_id=$1 AND recipient_user_id=$2)
   OR (sender_user_id=$2 AND recipient_user_id=$1)
ORDER BY created_at DESC
LIMIT 1
`

type GetMessageRequestBetweenParams struct {
	SenderUserID    string `json:"sender_user_id"`
	RecipientUserID string `json:"recipient_user_id"`
}

func (q *Queries) GetMessageRequestBetween(ctx context.Context, arg GetMessageRequestBetweenParams) (MessageRequest, error) {
	row := q.db.QueryRow(ctx, getMessageRequestBetween, arg.SenderUserID, arg.RecipientUserID)
	var i MessageRequest
	err := row.Scan(
		&i.ID,
		&i.SenderUserID,
		&i.RecipientUserID,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getNotificationPreference = `-- name: GetNotificationPreference :one
SELECT notifications_enabled FROM session_participants WHERE session_id=$1 AND user_id=$2
`

type GetNotificationPreferenceParams struct {
	SessionID string `json:"session_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) GetNotificationPreference(ctx context.Context, arg GetNotificationPreferenceParams) (bool, error) {
	row := q.db.QueryRow(ctx, getNotificationPreference, arg.SessionID, arg.UserID)
	var notifications_enabled bool
	err := row.Scan(&notifications_enabled)
	return notifications_enabled, err
}

const getOnboardingResume = `-- name: GetOnboardingResume :one
SELECT oc.step,COALESCE(oc.candidate_username,''),ap.username,ap.username_locked_at,ap.onboarding_completed_at FROM onboarding_checkpoints oc JOIN anonymous_profiles ap ON ap.user_id=oc.user_id WHERE oc.user_id=$1
`

type GetOnboardingResumeRow struct {
	Step                  string             `json:"step"`
	CandidateUsername     string             `json:"candidate_username"`
	Username              string             `json:"username"`
	UsernameLockedAt      pgtype.Timestamptz `json:"username_locked_at"`
	OnboardingCompletedAt pgtype.Timestamptz `json:"onboarding_completed_at"`
}

func (q *Queries) GetOnboardingResume(ctx context.Context, userID string) (GetOnboardingResumeRow, error) {
	row := q.db.QueryRow(ctx, getOnboardingResume, userID)
	var i GetOnboardingResumeRow
	err := row.Scan(
		&i.Step,
		&i.CandidateUsername,
		&i.Username,
		&i.UsernameLockedAt,
		&i.OnboardingCompletedAt,
	)
	return i, err
}

const getOwnProfile = `-- name: GetOwnProfile :one
SELECT user_id,username,username_normalized,avatar_storage_key,status_message FROM anonymous_profiles WHERE user_id=$1
`

type GetOwnProfileRow struct {
	UserID             string      `json:"user_id"`
	Username           string      `json:"username"`
	UsernameNormalized string      `json:"username_normalized"`
	AvatarStorageKey   pgtype.Text `json:"avatar_storage_key"`
	StatusMessage      string      `json:"status_message"`
}

func (q *Queries) GetOwnProfile(ctx context.Context, userID string) (GetOwnProfileRow, error) {
	row := q.db.QueryRow(ctx, getOwnProfile, userID)
	var i GetOwnProfileRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.UsernameNormalized,
		&i.AvatarStorageKey,
		&i.StatusMessage,
	)
	return i, err
}

const getPeerUserID = `-- name: GetPeerUserID :one
SELECT other.user_id FROM session_participants self JOIN session_participants other ON other.session_id=self.session_id AND other.user_id<>self.user_id WHERE self.session_id=$1 AND self.user_id=$2
`

type GetPeerUserIDParams struct {
	SessionID string `json:"session_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) GetPeerUserID(ctx context.Context, arg GetPeerUserIDParams) (string, error) {
	row := q.db.QueryRow(ctx, getPeerUserID, arg.SessionID, arg.UserID)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const getProfileByUsername = `-- name: GetProfileByUsername :one
SELECT user_id, username, username_normalized FROM anonymous_profiles WHERE username_normalized=$1
`

type GetProfileByUsernameRow struct {
	UserID             string `json:"user_id"`
	Username           string `json:"username"`
	UsernameNormalized string `json:"username_normalized"`
}

func (q *Queries) GetProfileByUsername(ctx context.Context, usernameNormalized string) (GetProfileByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getProfileByUsername, usernameNormalized)
	var i GetProfileByUsernameRow
	err := row.Scan(&i.UserID, &i.Username, &i.UsernameNormalized)
	return i, err
}

const getSessionRetention = `-- name: GetSessionRetention :one
SELECT retention_policy,retention_updated_at FROM chat_sessions WHERE id=$1
`

type GetSessionRetentionRow struct {
	RetentionPolicy    string             `json:"retention_policy"`
	RetentionUpdatedAt pgtype.Timestamptz `json:"retention_updated_at"`
}

func (q *Queries) GetSessionRetention(ctx context.Context, id string) (GetSessionRetentionRow, error) {
	row := q.db.QueryRow(ctx, getSessionRetention, id)
	var i GetSessionRetentionRow
	err := row.Scan(&i.RetentionPolicy, &i.RetentionUpdatedAt)
	return i, err
}

const getSettings = `-- name: GetSettings :one
SELECT theme,reduced_motion,send_on_enter,presence_visibility,read_receipts,notifications,avatar_visibility,status_visibility,notification_preview,notification_sound,quiet_hours_enabled,quiet_hours_start,quiet_hours_end,media_auto_download,link_previews_enabled,privacy_checkup_completed_at FROM user_settings WHERE user_id=$1
`

type GetSettingsRow struct {
	Theme                     string             `json:"theme"`
	ReducedMotion             bool               `json:"reduced_motion"`
	SendOnEnter               bool               `json:"send_on_enter"`
	PresenceVisibility        string             `json:"presence_visibility"`
	ReadReceipts              bool               `json:"read_receipts"`
	Notifications             bool               `json:"notifications"`
	AvatarVisibility          string             `json:"avatar_visibility"`
	StatusVisibility          string             `json:"status_visibility"`
	NotificationPreview       string             `json:"notification_preview"`
	NotificationSound         bool               `json:"notification_sound"`
	QuietHoursEnabled         bool               `json:"quiet_hours_enabled"`
	QuietHoursStart           pgtype.Time        `json:"quiet_hours_start"`
	QuietHoursEnd             pgtype.Time        `json:"quiet_hours_end"`
	MediaAutoDownload         string             `json:"media_auto_download"`
	LinkPreviewsEnabled       bool               `json:"link_previews_enabled"`
	PrivacyCheckupCompletedAt pgtype.Timestamptz `json:"privacy_checkup_completed_at"`
}

func (q *Queries) GetSettings(ctx context.Context, userID string) (GetSettingsRow, error) {
	row := q.db.QueryRow(ctx, getSettings, userID)
	var i GetSettingsRow
	err := row.Scan(
		&i.Theme,
		&i.ReducedMotion,
		&i.SendOnEnter,
		&i.PresenceVisibility,
		&i.ReadReceipts,
		&i.Notifications,
		&i.AvatarVisibility,
		&i.StatusVisibility,
		&i.NotificationPreview,
		&i.NotificationSound,
		&i.QuietHoursEnabled,
		&i.QuietHoursStart,
		&i.QuietHoursEnd,
		&i.MediaAutoDownload,
		&i.LinkPreviewsEnabled,
		&i.PrivacyCheckupCompletedAt,
	)
	return i, err
}

const getStorageUsage = `-- name: GetStorageUsage :one
SELECT COALESCE(SUM(ma.byte_size),0)::bigint,COUNT(*)::bigint FROM media_assets ma JOIN messages m ON m.id=ma.message_id WHERE m.sender_id=$1
`

type GetStorageUsageRow struct {
	Column1 int64 `json:"column_1"`
	Column2 int64 `json:"column_2"`
}

func (q *Queries) GetStorageUsage(ctx context.Context, senderID string) (GetStorageUsageRow, error) {
	row := q.db.QueryRow(ctx, getStorageUsage, senderID)
	var i GetStorageUsageRow
	err := row.Scan(&i.Column1, &i.Column2)
	return i, err
}

const isAccountEmailTaken = `-- name: IsAccountEmailTaken :one
SELECT EXISTS(SELECT 1 FROM accounts WHERE lower(email)=lower($1))
`

func (q *Queries) IsAccountEmailTaken(ctx context.Context, lower string) (bool, error) {
	row := q.db.QueryRow(ctx, isAccountEmailTaken, lower)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isAccountUsernameTaken = `-- name: IsAccountUsernameTaken :one
SELECT EXISTS(SELECT 1 FROM accounts WHERE username_normalized=$1)
`

func (q *Queries) IsAccountUsernameTaken(ctx context.Context, usernameNormalized string) (bool, error) {
	row := q.db.QueryRow(ctx, isAccountUsernameTaken, usernameNormalized)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isBlocked = `-- name: IsBlocked :one
SELECT EXISTS(SELECT 1 FROM blocked_users WHERE (blocker_id=$1 AND blocked_user_id=$2) OR (blocker_id=$2 AND blocked_user_id=$1))
`

type IsBlockedParams struct {
	BlockerID     string `json:"blocker_id"`
	BlockedUserID string `json:"blocked_user_id"`
}

func (q *Queries) IsBlocked(ctx context.Context, arg IsBlockedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isBlocked, arg.BlockerID, arg.BlockedUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isParticipant = `-- name: IsParticipant :one
SELECT EXISTS(SELECT 1 FROM session_participants WHERE session_id=$1 AND user_id=$2)
`

type IsParticipantParams struct {
	SessionID string `json:"session_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) IsParticipant(ctx context.Context, arg IsParticipantParams) (bool, error) {
	row := q.db.QueryRow(ctx, isParticipant, arg.SessionID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isProfileCompleted = `-- name: IsProfileCompleted :one
SELECT EXISTS(SELECT 1 FROM anonymous_profiles WHERE user_id=$1 AND onboarding_completed_at IS NOT NULL)
`

func (q *Queries) IsProfileCompleted(ctx context.Context, userID string) (bool, error) {
	row := q.db.QueryRow(ctx, isProfileCompleted, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isUsernameTaken = `-- name: IsUsernameTaken :one
SELECT EXISTS(SELECT 1 FROM anonymous_profiles WHERE username_normalized=$1 AND ($2='' OR user_id<>$2))
`

type IsUsernameTakenParams struct {
	UsernameNormalized string      `json:"username_normalized"`
	Column2            interface{} `json:"column_2"`
}

func (q *Queries) IsUsernameTaken(ctx context.Context, arg IsUsernameTakenParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUsernameTaken, arg.UsernameNormalized, arg.Column2)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const linkAccountUser = `-- name: LinkAccountUser :exec
UPDATE accounts SET linked_user_id=$1,updated_at=now() WHERE id=$2 AND linked_user_id IS NULL
`

type LinkAccountUserParams struct {
	LinkedUserID pgtype.Text `json:"linked_user_id"`
	ID           string      `json:"id"`
}

func (q *Queries) LinkAccountUser(ctx context.Context, arg LinkAccountUserParams) error {
	_, err := q.db.Exec(ctx, linkAccountUser, arg.LinkedUserID, arg.ID)
	return err
}

const listAccountSessions = `-- name: ListAccountSessions :many
SELECT id,created_at,last_seen_at,expires_at FROM account_sessions WHERE account_id=$1 AND revoked_at IS NULL AND expires_at>now() ORDER BY last_seen_at DESC
`

type ListAccountSessionsRow struct {
	ID         string             `json:"id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) ListAccountSessions(ctx context.Context, accountID string) ([]ListAccountSessionsRow, error) {
	rows, err := q.db.Query(ctx, listAccountSessions, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountSessionsRow{}
	for rows.Next() {
		var i ListAccountSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDataRightsRequests = `-- name: ListDataRightsRequests :many
SELECT id,request_kind,status,reference_code,confirmed_at,fulfilled_at,note,created_at,updated_at FROM data_rights_requests WHERE user_id=$1 ORDER BY created_at DESC
`

type ListDataRightsRequestsRow struct {
	ID            string             `json:"id"`
	RequestKind   string             `json:"request_kind"`
	Status        string             `json:"status"`
	ReferenceCode string             `json:"reference_code"`
	ConfirmedAt   pgtype.Timestamptz `json:"confirmed_at"`
	FulfilledAt   pgtype.Timestamptz `json:"fulfilled_at"`
	Note          pgtype.Text        `json:"note"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListDataRightsRequests(ctx context.Context, userID string) ([]ListDataRightsRequestsRow, error) {
	rows, err := q.db.Query(ctx, listDataRightsRequests, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDataRightsRequestsRow{}
	for rows.Next() {
		var i ListDataRightsRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestKind,
			&i.Status,
			&i.ReferenceCode,
			&i.ConfirmedAt,
			&i.FulfilledAt,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredMediaForDeletion = `-- name: ListExpiredMediaForDeletion :many
SELECT ma.id,ma.storage_key FROM media_assets ma JOIN messages m ON m.id=ma.message_id WHERE m.expires_at<=now() AND m.deleted_at IS NULL
`

type ListExpiredMediaForDeletionRow struct {
	ID         string `json:"id"`
	StorageKey string `json:"storage_key"`
}

func (q *Queries) ListExpiredMediaForDeletion(ctx context.Context) ([]ListExpiredMediaForDeletionRow, error) {
	rows, err := q.db.Query(ctx, listExpiredMediaForDeletion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredMediaForDeletionRow{}
	for rows.Next() {
		var i ListExpiredMediaForDeletionRow
		if err := rows.Scan(&i.ID, &i.StorageKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomingMessageRequests = `-- name: ListIncomingMessageRequests :many
SELECT mr.id,mr.sender_user_id,ap.username,mr.status,mr.created_at FROM message_requests mr JOIN anonymous_profiles ap ON ap.user_id=mr.sender_user_id WHERE mr.recipient_user_id=$1 AND mr.status='pending' ORDER BY mr.created_at DESC LIMIT $2
`

type ListIncomingMessageRequestsParams struct {
	RecipientUserID string `json:"recipient_user_id"`
	Limit           int32  `json:"limit"`
}

type ListIncomingMessageRequestsRow struct {
	ID           string             `json:"id"`
	SenderUserID string             `json:"sender_user_id"`
	Username     string             `json:"username"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListIncomingMessageRequests(ctx context.Context, arg ListIncomingMessageRequestsParams) ([]ListIncomingMessageRequestsRow, error) {
	rows, err := q.db.Query(ctx, listIncomingMessageRequests, arg.RecipientUserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIncomingMessageRequestsRow{}
	for rows.Next() {
		var i ListIncomingMessageRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderUserID,
			&i.Username,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id,session_id,sender_id,client_operation_id,cursor,kind,body,state,created_at FROM messages WHERE session_id=$1 ORDER BY cursor DESC LIMIT $2
`

type ListMessagesParams struct {
	SessionID string `json:"session_id"`
	Limit     int32  `json:"limit"`
}

type ListMessagesRow struct {
	ID                string             `json:"id"`
	SessionID         string             `json:"session_id"`
	SenderID          string             `json:"sender_id"`
	ClientOperationID string             `json:"client_operation_id"`
	Cursor            int64              `json:"cursor"`
	Kind              string             `json:"kind"`
	Body              pgtype.Text        `json:"body"`
	State             string             `json:"state"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error) {
	rows, err := q.db.Query(ctx, listMessages, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesRow{}
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.SenderID,
			&i.ClientOperationID,
			&i.Cursor,
			&i.Kind,
			&i.Body,
			&i.State,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesWithMedia = `-- name: ListMessagesWithMedia :many
SELECT m.id,m.session_id,m.sender_id,m.client_operation_id,m.cursor,m.kind,COALESCE(m.body,''),m.state,m.created_at,m.edited_at,m.deleted_at,m.expires_at,COALESCE((SELECT MAX(other.last_read_cursor) FROM session_participants other WHERE other.session_id=m.session_id AND other.user_id<>$3),0)>=m.cursor AS read,ma.storage_key,ma.file_name,ma.content_type,ma.byte_size FROM messages m LEFT JOIN media_assets ma ON ma.message_id=m.id WHERE m.session_id=$1 AND ($2::bigint=0 OR m.cursor<$2) ORDER BY m.cursor DESC LIMIT 51
`

type ListMessagesWithMediaParams struct {
	SessionID string `json:"session_id"`
	Column2   int64  `json:"column_2"`
	UserID    string `json:"user_id"`
}

type ListMessagesWithMediaRow struct {
	ID                string             `json:"id"`
	SessionID         string             `json:"session_id"`
	SenderID          string             `json:"sender_id"`
	ClientOperationID string             `json:"client_operation_id"`
	Cursor            int64              `json:"cursor"`
	Kind              string             `json:"kind"`
	Body              string             `json:"body"`
	State             string             `json:"state"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	EditedAt          pgtype.Timestamptz `json:"edited_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	Read              bool               `json:"read"`
	StorageKey        pgtype.Text        `json:"storage_key"`
	FileName          pgtype.Text        `json:"file_name"`
	ContentType       pgtype.Text        `json:"content_type"`
	ByteSize          pgtype.Int8        `json:"byte_size"`
}

func (q *Queries) ListMessagesWithMedia(ctx context.Context, arg ListMessagesWithMediaParams) ([]ListMessagesWithMediaRow, error) {
	rows, err := q.db.Query(ctx, listMessagesWithMedia, arg.SessionID, arg.Column2, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesWithMediaRow{}
	for rows.Next() {
		var i ListMessagesWithMediaRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.SenderID,
			&i.ClientOperationID,
			&i.Cursor,
			&i.Kind,
			&i.Body,
			&i.State,
			&i.CreatedAt,
			&i.EditedAt,
			&i.DeletedAt,
			&i.ExpiresAt,
			&i.Read,
			&i.StorageKey,
			&i.FileName,
			&i.ContentType,
			&i.ByteSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnExportMedia = `-- name: ListOwnExportMedia :many
SELECT ma.id,ma.message_id,ma.storage_key,ma.file_name,ma.content_type,ma.byte_size,ma.created_at FROM media_assets ma JOIN messages m ON m.id=ma.message_id WHERE m.sender_id=$1 ORDER BY ma.created_at ASC
`

func (q *Queries) ListOwnExportMedia(ctx context.Context, senderID string) ([]MediaAsset, error) {
	rows, err := q.db.Query(ctx, listOwnExportMedia, senderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaAsset{}
	for rows.Next() {
		var i MediaAsset
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.StorageKey,
			&i.FileName,
			&i.ContentType,
			&i.ByteSize,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnExportMessages = `-- name: ListOwnExportMessages :many
SELECT m.id,m.session_id,m.kind,COALESCE(m.body,''),m.state,m.created_at,m.edited_at,m.deleted_at FROM messages m WHERE m.sender_id=$1 ORDER BY m.created_at ASC
`

type ListOwnExportMessagesRow struct {
	ID        string             `json:"id"`
	SessionID string             `json:"session_id"`
	Kind      string             `json:"kind"`
	Body      string             `json:"body"`
	State     string             `json:"state"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	EditedAt  pgtype.Timestamptz `json:"edited_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListOwnExportMessages(ctx context.Context, senderID string) ([]ListOwnExportMessagesRow, error) {
	rows, err := q.db.Query(ctx, listOwnExportMessages, senderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOwnExportMessagesRow{}
	for rows.Next() {
		var i ListOwnExportMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Kind,
			&i.Body,
			&i.State,
			&i.CreatedAt,
			&i.EditedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnReports = `-- name: ListOwnReports :many
SELECT id,reference_code,status,reason,created_at FROM reports WHERE reporter_id=$1 ORDER BY created_at DESC LIMIT $2
`

type ListOwnReportsParams struct {
	ReporterID string `json:"reporter_id"`
	Limit      int32  `json:"limit"`
}

type ListOwnReportsRow struct {
	ID            string             `json:"id"`
	ReferenceCode string             `json:"reference_code"`
	Status        string             `json:"status"`
	Reason        string             `json:"reason"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListOwnReports(ctx context.Context, arg ListOwnReportsParams) ([]ListOwnReportsRow, error) {
	rows, err := q.db.Query(ctx, listOwnReports, arg.ReporterID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOwnReportsRow{}
	for rows.Next() {
		var i ListOwnReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReferenceCode,
			&i.Status,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionParticipants = `-- name: ListSessionParticipants :many
SELECT user_id FROM session_participants WHERE session_id=$1
`

func (q *Queries) ListSessionParticipants(ctx context.Context, sessionID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listSessionParticipants, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionSharedAssets = `-- name: ListSessionSharedAssets :many
SELECT m.id,m.session_id,m.sender_id,m.body,m.created_at,ma.storage_key,ma.file_name,ma.content_type,ma.byte_size FROM messages m JOIN session_participants sp ON sp.session_id=m.session_id AND sp.user_id=$1 JOIN media_assets ma ON ma.message_id=m.id WHERE m.session_id=$2 AND m.deleted_at IS NULL AND (($3='media' AND (ma.content_type LIKE 'image/%' OR ma.content_type LIKE 'video/%' OR ma.content_type LIKE 'audio/%')) OR ($3='documents' AND ma.content_type NOT LIKE 'image/%' AND ma.content_type NOT LIKE 'video/%' AND ma.content_type NOT LIKE 'audio/%')) ORDER BY m.created_at DESC LIMIT $4 OFFSET $5
`

type ListSessionSharedAssetsParams struct {
	UserID    string      `json:"user_id"`
	SessionID string      `json:"session_id"`
	Column3   interface{} `json:"column_3"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListSessionSharedAssetsRow struct {
	ID          string             `json:"id"`
	SessionID   string             `json:"session_id"`
	SenderID    string             `json:"sender_id"`
	Body        pgtype.Text        `json:"body"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	StorageKey  string             `json:"storage_key"`
	FileName    string             `json:"file_name"`
	ContentType string             `json:"content_type"`
	ByteSize    int64              `json:"byte_size"`
}

func (q *Queries) ListSessionSharedAssets(ctx context.Context, arg ListSessionSharedAssetsParams) ([]ListSessionSharedAssetsRow, error) {
	rows, err := q.db.Query(ctx, listSessionSharedAssets,
		arg.UserID,
		arg.SessionID,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionSharedAssetsRow{}
	for rows.Next() {
		var i ListSessionSharedAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.SenderID,
			&i.Body,
			&i.CreatedAt,
			&i.StorageKey,
			&i.FileName,
			&i.ContentType,
			&i.ByteSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionSharedLinks = `-- name: ListSessionSharedLinks :many
SELECT m.id,m.session_id,m.sender_id,m.body,m.created_at FROM messages m JOIN session_participants sp ON sp.session_id=m.session_id AND sp.user_id=$1 WHERE m.session_id=$2 AND m.deleted_at IS NULL AND COALESCE(m.body,'') ~* 'https?://[^[:space:]]+' ORDER BY m.created_at DESC LIMIT $3 OFFSET $4
`

type ListSessionSharedLinksParams struct {
	UserID    string `json:"user_id"`
	SessionID string `json:"session_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

type ListSessionSharedLinksRow struct {
	ID        string             `json:"id"`
	SessionID string             `json:"session_id"`
	SenderID  string             `json:"sender_id"`
	Body      pgtype.Text        `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListSessionSharedLinks(ctx context.Context, arg ListSessionSharedLinksParams) ([]ListSessionSharedLinksRow, error) {
	rows, err := q.db.Query(ctx, listSessionSharedLinks,
		arg.UserID,
		arg.SessionID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionSharedLinksRow{}
	for rows.Next() {
		var i ListSessionSharedLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.SenderID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT cs.id,ap.username,cs.last_activity_at,cs.retention_policy,COALESCE(sll.session_id IS NOT NULL,FALSE) AS local_locked FROM chat_sessions cs JOIN session_participants sp ON sp.session_id=cs.id AND sp.user_id=$1 JOIN session_participants other ON other.session_id=cs.id AND other.user_id<>$1 JOIN anonymous_profiles ap ON ap.user_id=other.user_id LEFT JOIN session_local_locks sll ON sll.session_id=cs.id AND sll.user_id=$1 WHERE sp.archived_at IS NULL ORDER BY cs.last_activity_at DESC
`

type ListSessionsRow struct {
	ID              string             `json:"id"`
	Username        string             `json:"username"`
	LastActivityAt  pgtype.Timestamptz `json:"last_activity_at"`
	RetentionPolicy string             `json:"retention_policy"`
	LocalLocked     interface{}        `json:"local_locked"`
}

func (q *Queries) ListSessions(ctx context.Context, userID string) ([]ListSessionsRow, error) {
	rows, err := q.db.Query(ctx, listSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsRow{}
	for rows.Next() {
		var i ListSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.LastActivityAt,
			&i.RetentionPolicy,
			&i.LocalLocked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMediaUsageOwner = `-- name: LockMediaUsageOwner :one
SELECT id FROM users WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockMediaUsageOwner(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockMediaUsageOwner, id)
	err := row.Scan(&id)
	return id, err
}

const lockUsername = `-- name: LockUsername :exec
UPDATE anonymous_profiles SET username=$1,username_normalized=$2,username_locked_at=now(),onboarding_completed_at=now(),updated_at=now() WHERE user_id=$3
`

type LockUsernameParams struct {
	Username           string `json:"username"`
	UsernameNormalized string `json:"username_normalized"`
	UserID             string `json:"user_id"`
}

func (q *Queries) LockUsername(ctx context.Context, arg LockUsernameParams) error {
	_, err := q.db.Exec(ctx, lockUsername, arg.Username, arg.UsernameNormalized, arg.UserID)
	return err
}

const markDeliveredMessages = `-- name: MarkDeliveredMessages :exec
UPDATE messages SET state='delivered' WHERE session_id=$1 AND sender_id<>$2 AND state='sent' AND deleted_at IS NULL
`

type MarkDeliveredMessagesParams struct {
	SessionID string `json:"session_id"`
	SenderID  string `json:"sender_id"`
}

func (q *Queries) MarkDeliveredMessages(ctx context.Context, arg MarkDeliveredMessagesParams) error {
	_, err := q.db.Exec(ctx, markDeliveredMessages, arg.SessionID, arg.SenderID)
	return err
}

const markParticipantRead = `-- name: MarkParticipantRead :one
UPDATE session_participants p SET last_read_cursor=GREATEST(p.last_read_cursor,m.cursor) FROM messages m WHERE p.session_id=$1 AND p.user_id=$2 AND m.id=$3 AND m.session_id=$1 RETURNING m.cursor
`

type MarkParticipantReadParams struct {
	SessionID string `json:"session_id"`
	UserID    string `json:"user_id"`
	ID        string `json:"id"`
}

func (q *Queries) MarkParticipantRead(ctx context.Context, arg MarkParticipantReadParams) (int64, error) {
	row := q.db.QueryRow(ctx, markParticipantRead, arg.SessionID, arg.UserID, arg.ID)
	var cursor int64
	err := row.Scan(&cursor)
	return cursor, err
}

const markReadMessages = `-- name: MarkReadMessages :exec
UPDATE messages SET state='read' WHERE session_id=$1 AND sender_id<>$2 AND cursor<=$3 AND state IN ('sent','delivered') AND deleted_at IS NULL
`

type MarkReadMessagesParams struct {
	SessionID string `json:"session_id"`
	SenderID  string `json:"sender_id"`
	Cursor    int64  `json:"cursor"`
}

func (q *Queries) MarkReadMessages(ctx context.Context, arg MarkReadMessagesParams) error {
	_, err := q.db.Exec(ctx, markReadMessages, arg.SessionID, arg.SenderID, arg.Cursor)
	return err
}

const muteSession = `-- name: MuteSession :exec
UPDATE session_participants SET muted_until=now()+($1 * interval '1 minute') WHERE session_id=$2 AND user_id=$3
`

type MuteSessionParams struct {
	Column1   interface{} `json:"column_1"`
	SessionID string      `json:"session_id"`
	UserID    string      `json:"user_id"`
}

func (q *Queries) MuteSession(ctx context.Context, arg MuteSessionParams) error {
	_, err := q.db.Exec(ctx, muteSession, arg.Column1, arg.SessionID, arg.UserID)
	return err
}

const nextMessageCursor = `-- name: NextMessageCursor :one
UPDATE chat_sessions
SET message_cursor=message_cursor+1,last_activity_at=now()
WHERE id=$1
RETURNING message_cursor
`

func (q *Queries) NextMessageCursor(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRow(ctx, nextMessageCursor, id)
	var message_cursor int64
	err := row.Scan(&message_cursor)
	return message_cursor, err
}

const removeSessionLocalLock = `-- name: RemoveSessionLocalLock :exec
DELETE FROM session_local_locks WHERE session_id=$1 AND user_id=$2
`

type RemoveSessionLocalLockParams struct {
	SessionID string `json:"session_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) RemoveSessionLocalLock(ctx context.Context, arg RemoveSessionLocalLockParams) error {
	_, err := q.db.Exec(ctx, removeSessionLocalLock, arg.SessionID, arg.UserID)
	return err
}

const resolveMessageRequest = `-- name: ResolveMessageRequest :one
UPDATE message_requests SET status=$1,resolved_at=now() WHERE id=$2 AND recipient_user_id=$3 AND status='pending' RETURNING id,sender_user_id,recipient_user_id,status,created_at,resolved_at
`

type ResolveMessageRequestParams struct {
	Status          string `json:"status"`
	ID              string `json:"id"`
	RecipientUserID string `json:"recipient_user_id"`
}

func (q *Queries) ResolveMessageRequest(ctx context.Context, arg ResolveMessageRequestParams) (MessageRequest, error) {
	row := q.db.QueryRow(ctx, resolveMessageRequest, arg.Status, arg.ID, arg.RecipientUserID)
	var i MessageRequest
	err := row.Scan(
		&i.ID,
		&i.SenderUserID,
		&i.RecipientUserID,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const revokeAccountSession = `-- name: RevokeAccountSession :exec
UPDATE account_sessions SET revoked_at=now() WHERE token_hash=$1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAccountSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeAccountSession, tokenHash)
	return err
}

const revokeAllAccountSessions = `-- name: RevokeAllAccountSessions :exec
UPDATE account_sessions SET revoked_at=now() WHERE account_id=$1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllAccountSessions(ctx context.Context, accountID string) error {
	_, err := q.db.Exec(ctx, revokeAllAccountSessions, accountID)
	return err
}

const revokeBrowserSession = `-- name: RevokeBrowserSession :exec
UPDATE browser_sessions SET revoked_at=now() WHERE token_hash=$1 AND revoked_at IS NULL
`

func (q *Queries) RevokeBrowserSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeBrowserSession, tokenHash)
	return err
}

const searchMessages = `-- name: SearchMessages :many
SELECT m.id,m.session_id,m.body,m.cursor,ap.username FROM messages m JOIN session_participants sp ON sp.session_id=m.session_id AND sp.user_id=$1 JOIN session_participants other ON other.session_id=m.session_id AND other.user_id<>$1 JOIN anonymous_profiles ap ON ap.user_id=other.user_id WHERE m.deleted_at IS NULL AND COALESCE(m.body,'') ILIKE $2 ORDER BY m.created_at DESC LIMIT $3
`

type SearchMessagesParams struct {
	UserID string      `json:"user_id"`
	Body   pgtype.Text `json:"body"`
	Limit  int32       `json:"limit"`
}

type SearchMessagesRow struct {
	ID        string      `json:"id"`
	SessionID string      `json:"session_id"`
	Body      pgtype.Text `json:"body"`
	Cursor    int64       `json:"cursor"`
	Username  string      `json:"username"`
}

func (q *Queries) SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]SearchMessagesRow, error) {
	rows, err := q.db.Query(ctx, searchMessages, arg.UserID, arg.Body, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMessagesRow{}
	for rows.Next() {
		var i SearchMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Body,
			&i.Cursor,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProfiles = `-- name: SearchProfiles :many
SELECT ap.user_id,ap.username FROM anonymous_profiles ap WHERE ap.onboarding_completed_at IS NOT NULL AND ap.user_id<>$1 AND ap.username_normalized ILIKE $2 AND NOT EXISTS (SELECT 1 FROM blocked_users b WHERE (b.blocker_id=$1 AND b.blocked_user_id=ap.user_id) OR (b.blocker_id=ap.user_id AND b.blocked_user_id=$1)) ORDER BY ap.username_normalized LIMIT $3
`

type SearchProfilesParams struct {
	UserID             string `json:"user_id"`
	UsernameNormalized string `json:"username_normalized"`
	Limit              int32  `json:"limit"`
}

type SearchProfilesRow struct {
	UserID   string `json:"user_id"`
	Username string `json:"username"`
}

func (q *Queries) SearchProfiles(ctx context.Context, arg SearchProfilesParams) ([]SearchProfilesRow, error) {
	rows, err := q.db.Query(ctx, searchProfiles, arg.UserID, arg.UsernameNormalized, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchProfilesRow{}
	for rows.Next() {
		var i SearchProfilesRow
		if err := rows.Scan(&i.UserID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSessionMessages = `-- name: SearchSessionMessages :many
SELECT id,session_id,sender_id,body,cursor,state,created_at FROM messages WHERE session_id=$1 AND deleted_at IS NULL AND COALESCE(body,'') ILIKE $2 AND ($3='' OR created_at >= $3::timestamptz) AND ($4='' OR created_at < ($4::date + INTERVAL '1 day')) ORDER BY created_at DESC LIMIT $5 OFFSET $6
`

type SearchSessionMessagesParams struct {
	SessionID string      `json:"session_id"`
	Body      pgtype.Text `json:"body"`
	Column3   interface{} `json:"column_3"`
	Column4   interface{} `json:"column_4"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type SearchSessionMessagesRow struct {
	ID        string             `json:"id"`
	SessionID string             `json:"session_id"`
	SenderID  string             `json:"sender_id"`
	Body      pgtype.Text        `json:"body"`
	Cursor    int64              `json:"cursor"`
	State     string             `json:"state"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) SearchSessionMessages(ctx context.Context, arg SearchSessionMessagesParams) ([]SearchSessionMessagesRow, error) {
	rows, err := q.db.Query(ctx, searchSessionMessages,
		arg.SessionID,
		arg.Body,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchSessionMessagesRow{}
	for rows.Next() {
		var i SearchSessionMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.SenderID,
			&i.Body,
			&i.Cursor,
			&i.State,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNotificationPreference = `-- name: SetNotificationPreference :exec
UPDATE session_participants SET notifications_enabled=$1 WHERE session_id=$2 AND user_id=$3
`

type SetNotificationPreferenceParams struct {
	NotificationsEnabled bool   `json:"notifications_enabled"`
	SessionID            string `json:"session_id"`
	UserID               string `json:"user_id"`
}

func (q *Queries) SetNotificationPreference(ctx context.Context, arg SetNotificationPreferenceParams) error {
	_, err := q.db.Exec(ctx, setNotificationPreference, arg.NotificationsEnabled, arg.SessionID, arg.UserID)
	return err
}

const setSessionLocalLock = `-- name: SetSessionLocalLock :exec
INSERT INTO session_local_locks (session_id,user_id) VALUES ($1,$2) ON CONFLICT(session_id,user_id) DO UPDATE SET locked_at=now(),last_verified_at=now()
`

type SetSessionLocalLockParams struct {
	SessionID string `json:"session_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) SetSessionLocalLock(ctx context.Context, arg SetSessionLocalLockParams) error {
	_, err := q.db.Exec(ctx, setSessionLocalLock, arg.SessionID, arg.UserID)
	return err
}

const setSessionRetention = `-- name: SetSessionRetention :exec
UPDATE chat_sessions SET retention_policy=$1,retention_updated_at=now() WHERE id=$2
`

type SetSessionRetentionParams struct {
	RetentionPolicy string `json:"retention_policy"`
	ID              string `json:"id"`
}

func (q *Queries) SetSessionRetention(ctx context.Context, arg SetSessionRetentionParams) error {
	_, err := q.db.Exec(ctx, setSessionRetention, arg.RetentionPolicy, arg.ID)
	return err
}

const touchAccountSession = `-- name: TouchAccountSession :exec
UPDATE account_sessions SET last_seen_at=now() WHERE token_hash=$1 AND revoked_at IS NULL
`

func (q *Queries) TouchAccountSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, touchAccountSession, tokenHash)
	return err
}

const updateAccountSignedIn = `-- name: UpdateAccountSignedIn :exec
UPDATE accounts SET last_signed_in_at=now(),updated_at=now() WHERE id=$1
`

func (q *Queries) UpdateAccountSignedIn(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateAccountSignedIn, id)
	return err
}

const updateMessageBody = `-- name: UpdateMessageBody :one
UPDATE messages SET body=$1, edited_at=now() WHERE id=$2 AND session_id=$3 AND sender_id=$4 AND deleted_at IS NULL RETURNING id,session_id,sender_id,client_operation_id,cursor,kind,body,state,created_at,edited_at,deleted_at,false
`

type UpdateMessageBodyParams struct {
	Body      pgtype.Text `json:"body"`
	ID        string      `json:"id"`
	SessionID string      `json:"session_id"`
	SenderID  string      `json:"sender_id"`
}

type UpdateMessageBodyRow struct {
	ID                string             `json:"id"`
	SessionID         string             `json:"session_id"`
	SenderID          string             `json:"sender_id"`
	ClientOperationID string             `json:"client_operation_id"`
	Cursor            int64              `json:"cursor"`
	Kind              string             `json:"kind"`
	Body              pgtype.Text        `json:"body"`
	State             string             `json:"state"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	EditedAt          pgtype.Timestamptz `json:"edited_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	Column12          bool               `json:"column_12"`
}

func (q *Queries) UpdateMessageBody(ctx context.Context, arg UpdateMessageBodyParams) (UpdateMessageBodyRow, error) {
	row := q.db.QueryRow(ctx, updateMessageBody,
		arg.Body,
		arg.ID,
		arg.SessionID,
		arg.SenderID,
	)
	var i UpdateMessageBodyRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.SenderID,
		&i.ClientOperationID,
		&i.Cursor,
		&i.Kind,
		&i.Body,
		&i.State,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
		&i.Column12,
	)
	return i, err
}

const updateOwnProfile = `-- name: UpdateOwnProfile :one
UPDATE anonymous_profiles SET avatar_storage_key=COALESCE($2,avatar_storage_key), status_message=COALESCE($3,status_message), updated_at=now() WHERE user_id=$1 RETURNING user_id,username,username_normalized,avatar_storage_key,status_message
`

type UpdateOwnProfileParams struct {
	UserID           string      `json:"user_id"`
	AvatarStorageKey pgtype.Text `json:"avatar_storage_key"`
	StatusMessage    pgtype.Text `json:"status_message"`
}

type UpdateOwnProfileRow struct {
	UserID             string      `json:"user_id"`
	Username           string      `json:"username"`
	UsernameNormalized string      `json:"username_normalized"`
	AvatarStorageKey   pgtype.Text `json:"avatar_storage_key"`
	StatusMessage      string      `json:"status_message"`
}

func (q *Queries) UpdateOwnProfile(ctx context.Context, arg UpdateOwnProfileParams) (UpdateOwnProfileRow, error) {
	row := q.db.QueryRow(ctx, updateOwnProfile, arg.UserID, arg.AvatarStorageKey, arg.StatusMessage)
	var i UpdateOwnProfileRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.UsernameNormalized,
		&i.AvatarStorageKey,
		&i.StatusMessage,
	)
	return i, err
}

const updateSettings = `-- name: UpdateSettings :exec
UPDATE user_settings SET theme=COALESCE(NULLIF($2,''),theme), reduced_motion=COALESCE($3,reduced_motion), send_on_enter=COALESCE($4,send_on_enter), presence_visibility=COALESCE(NULLIF($5,''),presence_visibility), read_receipts=COALESCE($6,read_receipts), notifications=COALESCE($7,notifications), avatar_visibility=COALESCE(NULLIF($8,''),avatar_visibility), status_visibility=COALESCE(NULLIF($9,''),status_visibility), notification_preview=COALESCE(NULLIF($10,''),notification_preview), notification_sound=COALESCE($11,notification_sound), quiet_hours_enabled=COALESCE($12,quiet_hours_enabled), quiet_hours_start=COALESCE($13,quiet_hours_start), quiet_hours_end=COALESCE($14,quiet_hours_end), media_auto_download=COALESCE(NULLIF($15,''),media_auto_download), link_previews_enabled=COALESCE($16,link_previews_enabled), privacy_checkup_completed_at=CASE WHEN $17::boolean THEN now() ELSE privacy_checkup_completed_at END, updated_at=now() WHERE user_id=$1
`

type UpdateSettingsParams struct {
	UserID                 string      `json:"user_id"`
	Theme                  interface{} `json:"theme"`
	ReducedMotion          pgtype.Bool `json:"reduced_motion"`
	SendOnEnter            pgtype.Bool `json:"send_on_enter"`
	PresenceVisibility     interface{} `json:"presence_visibility"`
	ReadReceipts           pgtype.Bool `json:"read_receipts"`
	Notifications          pgtype.Bool `json:"notifications"`
	AvatarVisibility       interface{} `json:"avatar_visibility"`
	StatusVisibility       interface{} `json:"status_visibility"`
	NotificationPreview    interface{} `json:"notification_preview"`
	NotificationSound      pgtype.Bool `json:"notification_sound"`
	QuietHoursEnabled      pgtype.Bool `json:"quiet_hours_enabled"`
	QuietHoursStart        pgtype.Time `json:"quiet_hours_start"`
	QuietHoursEnd          pgtype.Time `json:"quiet_hours_end"`
	MediaAutoDownload      interface{} `json:"media_auto_download"`
	LinkPreviewsEnabled    pgtype.Bool `json:"link_previews_enabled"`
	PrivacyCheckupComplete pgtype.Bool `json:"privacy_checkup_complete"`
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) error {
	_, err := q.db.Exec(ctx, updateSettings,
		arg.UserID,
		arg.Theme,
		arg.ReducedMotion,
		arg.SendOnEnter,
		arg.PresenceVisibility,
		arg.ReadReceipts,
		arg.Notifications,
		arg.AvatarVisibility,
		arg.StatusVisibility,
		arg.NotificationPreview,
		arg.NotificationSound,
		arg.QuietHoursEnabled,
		arg.QuietHoursStart,
		arg.QuietHoursEnd,
		arg.MediaAutoDownload,
		arg.LinkPreviewsEnabled,
		arg.PrivacyCheckupComplete,
	)
	return err
}

const upsertCheckpoint = `-- name: UpsertCheckpoint :one
INSERT INTO onboarding_checkpoints (user_id, step, candidate_username) VALUES ($1,$2,$3) ON CONFLICT(user_id) DO UPDATE SET step=EXCLUDED.step,candidate_username=EXCLUDED.candidate_username,updated_at=now() RETURNING user_id, step, candidate_username
`

type UpsertCheckpointParams struct {
	UserID            string      `json:"user_id"`
	Step              string      `json:"step"`
	CandidateUsername pgtype.Text `json:"candidate_username"`
}

type UpsertCheckpointRow struct {
	UserID            string      `json:"user_id"`
	Step              string      `json:"step"`
	CandidateUsername pgtype.Text `json:"candidate_username"`
}

func (q *Queries) UpsertCheckpoint(ctx context.Context, arg UpsertCheckpointParams) (UpsertCheckpointRow, error) {
	row := q.db.QueryRow(ctx, upsertCheckpoint, arg.UserID, arg.Step, arg.CandidateUsername)
	var i UpsertCheckpointRow
	err := row.Scan(&i.UserID, &i.Step, &i.CandidateUsername)
	return i, err
}

const upsertMediaAsset = `-- name: UpsertMediaAsset :one
INSERT INTO media_assets (id,message_id,storage_key,file_name,content_type,byte_size) VALUES ($1,$2,$3,$4,$5,$6) ON CONFLICT(message_id) DO UPDATE SET message_id=EXCLUDED.message_id RETURNING storage_key,file_name,content_type,byte_size
`

type UpsertMediaAssetParams struct {
	ID          string `json:"id"`
	MessageID   string `json:"message_id"`
	StorageKey  string `json:"storage_key"`
	FileName    string `json:"file_name"`
	ContentType string `json:"content_type"`
	ByteSize    int64  `json:"byte_size"`
}

type UpsertMediaAssetRow struct {
	StorageKey  string `json:"storage_key"`
	FileName    string `json:"file_name"`
	ContentType string `json:"content_type"`
	ByteSize    int64  `json:"byte_size"`
}

func (q *Queries) UpsertMediaAsset(ctx context.Context, arg UpsertMediaAssetParams) (UpsertMediaAssetRow, error) {
	row := q.db.QueryRow(ctx, upsertMediaAsset,
		arg.ID,
		arg.MessageID,
		arg.StorageKey,
		arg.FileName,
		arg.ContentType,
		arg.ByteSize,
	)
	var i UpsertMediaAssetRow
	err := row.Scan(
		&i.StorageKey,
		&i.FileName,
		&i.ContentType,
		&i.ByteSize,
	)
	return i, err
}
