// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                 string             `json:"id"`
	Username           string             `json:"username"`
	UsernameNormalized string             `json:"username_normalized"`
	Email              string             `json:"email"`
	PasswordHash       string             `json:"password_hash"`
	LinkedUserID       pgtype.Text        `json:"linked_user_id"`
	Status             string             `json:"status"`
	EmailVerifiedAt    pgtype.Timestamptz `json:"email_verified_at"`
	LastSignedInAt     pgtype.Timestamptz `json:"last_signed_in_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type AccountSession struct {
	ID         string             `json:"id"`
	AccountID  string             `json:"account_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AnonymousProfile struct {
	UserID                string             `json:"user_id"`
	Username              string             `json:"username"`
	UsernameNormalized    string             `json:"username_normalized"`
	IdentitySeed          string             `json:"identity_seed"`
	UsernameLockedAt      pgtype.Timestamptz `json:"username_locked_at"`
	OnboardingCompletedAt pgtype.Timestamptz `json:"onboarding_completed_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	AvatarStorageKey      pgtype.Text        `json:"avatar_storage_key"`
	StatusMessage         string             `json:"status_message"`
}

type BlockedUser struct {
	BlockerID     string             `json:"blocker_id"`
	BlockedUserID string             `json:"blocked_user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type BrowserSession struct {
	ID         string             `json:"id"`
	UserID     string             `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	CsrfHash   string             `json:"csrf_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ChatSession struct {
	ID                 string             `json:"id"`
	DirectPairKey      string             `json:"direct_pair_key"`
	Status             string             `json:"status"`
	LastActivityAt     pgtype.Timestamptz `json:"last_activity_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	RetentionPolicy    string             `json:"retention_policy"`
	RetentionUpdatedAt pgtype.Timestamptz `json:"retention_updated_at"`
	MessageCursor      int64              `json:"message_cursor"`
}

type DataRightsRequest struct {
	ID            string             `json:"id"`
	UserID        string             `json:"user_id"`
	RequestKind   string             `json:"request_kind"`
	Status        string             `json:"status"`
	ReferenceCode string             `json:"reference_code"`
	ConfirmedAt   pgtype.Timestamptz `json:"confirmed_at"`
	FulfilledAt   pgtype.Timestamptz `json:"fulfilled_at"`
	Note          pgtype.Text        `json:"note"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type MediaAsset struct {
	ID          string             `json:"id"`
	MessageID   string             `json:"message_id"`
	StorageKey  string             `json:"storage_key"`
	FileName    string             `json:"file_name"`
	ContentType string             `json:"content_type"`
	ByteSize    int64              `json:"byte_size"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type MemoryVault struct {
	ID        string             `json:"id"`
	SessionID string             `json:"session_id"`
	State     string             `json:"state"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Message struct {
	ID                string             `json:"id"`
	SessionID         string             `json:"session_id"`
	SenderID          string             `json:"sender_id"`
	ClientOperationID string             `json:"client_operation_id"`
	Cursor            int64              `json:"cursor"`
	Kind              string             `json:"kind"`
	Body              pgtype.Text        `json:"body"`
	State             string             `json:"state"`
	EditedAt          pgtype.Timestamptz `json:"edited_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	ExpiredAt         pgtype.Timestamptz `json:"expired_at"`
}

type MessageRequest struct {
	ID              string             `json:"id"`
	SenderUserID    string             `json:"sender_user_id"`
	RecipientUserID string             `json:"recipient_user_id"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ResolvedAt      pgtype.Timestamptz `json:"resolved_at"`
}

type OnboardingCheckpoint struct {
	UserID            string             `json:"user_id"`
	Step              string             `json:"step"`
	CandidateUsername pgtype.Text        `json:"candidate_username"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Report struct {
	ID             string             `json:"id"`
	ReporterID     string             `json:"reporter_id"`
	ReportedUserID string             `json:"reported_user_id"`
	SessionID      string             `json:"session_id"`
	Reason         string             `json:"reason"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Status         string             `json:"status"`
	ReferenceCode  string             `json:"reference_code"`
}

type RetentionEvent struct {
	ID             string             `json:"id"`
	SessionID      string             `json:"session_id"`
	ActorUserID    string             `json:"actor_user_id"`
	PreviousPolicy string             `json:"previous_policy"`
	NextPolicy     string             `json:"next_policy"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type SessionLocalLock struct {
	SessionID      string             `json:"session_id"`
	UserID         string             `json:"user_id"`
	LockedAt       pgtype.Timestamptz `json:"locked_at"`
	LastVerifiedAt pgtype.Timestamptz `json:"last_verified_at"`
}

type SessionParticipant struct {
	SessionID            string             `json:"session_id"`
	UserID               string             `json:"user_id"`
	JoinedAt             pgtype.Timestamptz `json:"joined_at"`
	ArchivedAt           pgtype.Timestamptz `json:"archived_at"`
	MutedUntil           pgtype.Timestamptz `json:"muted_until"`
	LastReadCursor       int64              `json:"last_read_cursor"`
	NotificationsEnabled bool               `json:"notifications_enabled"`
}

type User struct {
	ID        string             `json:"id"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserSetting struct {
	UserID                    string             `json:"user_id"`
	Theme                     string             `json:"theme"`
	ReducedMotion             bool               `json:"reduced_motion"`
	SendOnEnter               bool               `json:"send_on_enter"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	PresenceVisibility        string             `json:"presence_visibility"`
	ReadReceipts              bool               `json:"read_receipts"`
	Notifications             bool               `json:"notifications"`
	AvatarVisibility          string             `json:"avatar_visibility"`
	StatusVisibility          string             `json:"status_visibility"`
	NotificationPreview       string             `json:"notification_preview"`
	NotificationSound         bool               `json:"notification_sound"`
	QuietHoursEnabled         bool               `json:"quiet_hours_enabled"`
	QuietHoursStart           pgtype.Time        `json:"quiet_hours_start"`
	QuietHoursEnd             pgtype.Time        `json:"quiet_hours_end"`
	MediaAutoDownload         string             `json:"media_auto_download"`
	LinkPreviewsEnabled       bool               `json:"link_previews_enabled"`
	PrivacyCheckupCompletedAt pgtype.Timestamptz `json:"privacy_checkup_completed_at"`
}
