// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddMediaMessage(ctx context.Context, arg AddMediaMessageParams) (AddMediaMessageRow, error)
	AddParticipant(ctx context.Context, arg AddParticipantParams) error
	ArchiveSession(ctx context.Context, arg ArchiveSessionParams) error
	ClearOwnProfileAvatar(ctx context.Context, userID string) (ClearOwnProfileAvatarRow, error)
	CompleteOnboardingCheckpoint(ctx context.Context, arg CompleteOnboardingCheckpointParams) error
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateAccountSession(ctx context.Context, arg CreateAccountSessionParams) error
	CreateBlock(ctx context.Context, arg CreateBlockParams) error
	CreateBrowserSession(ctx context.Context, arg CreateBrowserSessionParams) error
	CreateDataDeletionRequest(ctx context.Context, arg CreateDataDeletionRequestParams) (CreateDataDeletionRequestRow, error)
	CreateDirectSession(ctx context.Context, arg CreateDirectSessionParams) (CreateDirectSessionRow, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (CreateMessageRow, error)
	CreateMessageRequest(ctx context.Context, arg CreateMessageRequestParams) (MessageRequest, error)
	CreateProfile(ctx context.Context, arg CreateProfileParams) (CreateProfileRow, error)
	CreateReport(ctx context.Context, arg CreateReportParams) error
	CreateReportReceipt(ctx context.Context, arg CreateReportReceiptParams) (CreateReportReceiptRow, error)
	CreateRetentionEvent(ctx context.Context, arg CreateRetentionEventParams) error
	CreateUser(ctx context.Context, id string) (User, error)
	CreateUserSettings(ctx context.Context, userID string) error
	DeleteMediaAsset(ctx context.Context, id string) error
	DeleteMessage(ctx context.Context, arg DeleteMessageParams) (string, error)
	ExpireDueMessages(ctx context.Context) ([]ExpireDueMessagesRow, error)
	GetAccountByID(ctx context.Context, id string) (Account, error)
	GetAccountByIdentifier(ctx context.Context, usernameNormalized string) (Account, error)
	GetAccountForUser(ctx context.Context, linkedUserID pgtype.Text) (Account, error)
	GetAccountSession(ctx context.Context, tokenHash string) (string, error)
	GetBrowserSessionUser(ctx context.Context, tokenHash string) (string, error)
	GetDirectSessionByPair(ctx context.Context, directPairKey string) (GetDirectSessionByPairRow, error)
	GetMediaMessageByOperation(ctx context.Context, arg GetMediaMessageByOperationParams) (GetMediaMessageByOperationRow, error)
	GetMessageCursor(ctx context.Context, arg GetMessageCursorParams) (int64, error)
	GetMessageRequestBetween(ctx context.Context, arg GetMessageRequestBetweenParams) (MessageRequest, error)
	GetNotificationPreference(ctx context.Context, arg GetNotificationPreferenceParams) (bool, error)
	GetOnboardingResume(ctx context.Context, userID string) (GetOnboardingResumeRow, error)
	GetOwnProfile(ctx context.Context, userID string) (GetOwnProfileRow, error)
	GetPeerUserID(ctx context.Context, arg GetPeerUserIDParams) (string, error)
	GetProfileByUsername(ctx context.Context, usernameNormalized string) (GetProfileByUsernameRow, error)
	GetSessionRetention(ctx context.Context, id string) (GetSessionRetentionRow, error)
	GetSettings(ctx context.Context, userID string) (GetSettingsRow, error)
	GetStorageUsage(ctx context.Context, senderID string) (GetStorageUsageRow, error)
	IsAccountEmailTaken(ctx context.Context, lower string) (bool, error)
	IsAccountUsernameTaken(ctx context.Context, usernameNormalized string) (bool, error)
	IsBlocked(ctx context.Context, arg IsBlockedParams) (bool, error)
	IsParticipant(ctx context.Context, arg IsParticipantParams) (bool, error)
	IsProfileCompleted(ctx context.Context, userID string) (bool, error)
	IsUsernameTaken(ctx context.Context, arg IsUsernameTakenParams) (bool, error)
	LinkAccountUser(ctx context.Context, arg LinkAccountUserParams) error
	ListAccountSessions(ctx context.Context, accountID string) ([]ListAccountSessionsRow, error)
	ListDataRightsRequests(ctx context.Context, userID string) ([]ListDataRightsRequestsRow, error)
	ListExpiredMediaForDeletion(ctx context.Context) ([]ListExpiredMediaForDeletionRow, error)
	ListIncomingMessageRequests(ctx context.Context, arg ListIncomingMessageRequestsParams) ([]ListIncomingMessageRequestsRow, error)
	ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error)
	ListMessagesWithMedia(ctx context.Context, arg ListMessagesWithMediaParams) ([]ListMessagesWithMediaRow, error)
	ListOwnExportMedia(ctx context.Context, senderID string) ([]MediaAsset, error)
	ListOwnExportMessages(ctx context.Context, senderID string) ([]ListOwnExportMessagesRow, error)
	ListOwnReports(ctx context.Context, arg ListOwnReportsParams) ([]ListOwnReportsRow, error)
	ListSessionParticipants(ctx context.Context, sessionID string) ([]string, error)
	ListSessionSharedAssets(ctx context.Context, arg ListSessionSharedAssetsParams) ([]ListSessionSharedAssetsRow, error)
	ListSessionSharedLinks(ctx context.Context, arg ListSessionSharedLinksParams) ([]ListSessionSharedLinksRow, error)
	ListSessions(ctx context.Context, userID string) ([]ListSessionsRow, error)
	LockMediaUsageOwner(ctx context.Context, id string) (string, error)
	LockUsername(ctx context.Context, arg LockUsernameParams) error
	MarkDeliveredMessages(ctx context.Context, arg MarkDeliveredMessagesParams) error
	MarkParticipantRead(ctx context.Context, arg MarkParticipantReadParams) (int64, error)
	MarkReadMessages(ctx context.Context, arg MarkReadMessagesParams) error
	MuteSession(ctx context.Context, arg MuteSessionParams) error
	NextMessageCursor(ctx context.Context, id string) (int64, error)
	RemoveSessionLocalLock(ctx context.Context, arg RemoveSessionLocalLockParams) error
	ResolveMessageRequest(ctx context.Context, arg ResolveMessageRequestParams) (MessageRequest, error)
	RevokeAccountSession(ctx context.Context, tokenHash string) error
	RevokeAllAccountSessions(ctx context.Context, accountID string) error
	RevokeBrowserSession(ctx context.Context, tokenHash string) error
	SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]SearchMessagesRow, error)
	SearchProfiles(ctx context.Context, arg SearchProfilesParams) ([]SearchProfilesRow, error)
	SearchSessionMessages(ctx context.Context, arg SearchSessionMessagesParams) ([]SearchSessionMessagesRow, error)
	SetNotificationPreference(ctx context.Context, arg SetNotificationPreferenceParams) error
	SetSessionLocalLock(ctx context.Context, arg SetSessionLocalLockParams) error
	SetSessionRetention(ctx context.Context, arg SetSessionRetentionParams) error
	TouchAccountSession(ctx context.Context, tokenHash string) error
	UpdateAccountSignedIn(ctx context.Context, id string) error
	UpdateMessageBody(ctx context.Context, arg UpdateMessageBodyParams) (UpdateMessageBodyRow, error)
	UpdateOwnProfile(ctx context.Context, arg UpdateOwnProfileParams) (UpdateOwnProfileRow, error)
	UpdateSettings(ctx context.Context, arg UpdateSettingsParams) error
	UpsertCheckpoint(ctx context.Context, arg UpsertCheckpointParams) (UpsertCheckpointRow, error)
	UpsertMediaAsset(ctx context.Context, arg UpsertMediaAssetParams) (UpsertMediaAssetRow, error)
}

var _ Querier = (*Queries)(nil)
