package main

import (
	"database/sql"
	"fmt"
	"os"
	"strings"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/stdlib"
	"github.com/pressly/goose/v3"
)

func main() {
	postgresURL := strings.ReplaceAll(os.Getenv("GOCHAT_POSTGRES_URL"), `\u0026`, "&")
	if postgresURL == "" {
		panic("GOCHAT_POSTGRES_URL is required")
	}

	connConfig, err := pgx.ParseConfig(postgresURL)
	if err != nil {
		panic(fmt.Errorf("parse PostgreSQL URL: %w", err))
	}
	connConfig.DefaultQueryExecMode = pgx.QueryExecModeSimpleProtocol
	db := stdlib.OpenDB(*connConfig)
	if err != nil {
		panic(fmt.Errorf("open PostgreSQL: %w", err))
	}
	defer db.Close()
	if err := db.Ping(); err != nil {
		panic(fmt.Errorf("ping PostgreSQL: %w", err))
	}
	if err := goose.SetDialect("postgres"); err != nil {
		panic(fmt.Errorf("configure goose: %w", err))
	}
	if _, err := db.Exec(`CREATE TABLE IF NOT EXISTS goose_db_version (id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, version_id bigint NOT NULL, is_applied boolean NOT NULL, tstamp timestamp NOT NULL DEFAULT now())`); err != nil {
		panic(fmt.Errorf("create Goose version table: %w", err))
	}
	var hasCore bool
	if err := db.QueryRow(`SELECT to_regclass('public.users') IS NOT NULL`).Scan(&hasCore); err != nil {
		panic(fmt.Errorf("detect core schema: %w", err))
	}
	var currentVersion sql.NullInt64
	if err := db.QueryRow(`SELECT max(version_id) FROM goose_db_version`).Scan(&currentVersion); err != nil {
		panic(fmt.Errorf("read Goose version: %w", err))
	}
	if hasCore && (!currentVersion.Valid || currentVersion.Int64 < 1) {
		if _, err := db.Exec(`INSERT INTO goose_db_version (version_id,is_applied) VALUES (1,true)`); err != nil {
			panic(fmt.Errorf("baseline core migration: %w", err))
		}
	}
	if err := goose.Up(db, "backend/migrations"); err != nil {
		panic(fmt.Errorf("apply Goose migrations: %w", err))
	}
	fmt.Println("Go Chat PostgreSQL migrations are current")
}
