export function ConversationStageStyles() {
  return <style>{`
    .conversation-stage{--stage-edge:color-mix(in srgb,var(--signal) 42%,transparent);--stage-grid:rgba(255,255,255,.024);position:relative;isolation:isolate;border-color:color-mix(in srgb,var(--border-strong) 78%,transparent)!important;border-radius:24px!important;background:linear-gradient(132deg,color-mix(in srgb,var(--surface-raised) 96%,#07080e 4%),color-mix(in srgb,var(--surface) 89%,#07080e 11%))!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.055),0 28px 76px rgba(0,0,0,.22)!important}
    .conversation-stage::before{position:absolute;z-index:-1;inset:0;border-radius:inherit;background-image:linear-gradient(var(--stage-grid) 1px,transparent 1px),linear-gradient(90deg,var(--stage-grid) 1px,transparent 1px);background-size:38px 38px;mask-image:linear-gradient(to bottom,black,transparent 55%);content:"";pointer-events:none}
    .conversation-stage>header{min-height:68px;padding-inline:20px!important;border-bottom-color:color-mix(in srgb,var(--border) 90%,transparent)!important;background:linear-gradient(90deg,rgba(255,255,255,.022),transparent 68%)}
    .conversation-stage>header::after{display:inline-flex;order:-1;align-items:center;min-width:5px;height:5px;margin-right:-3px;border-radius:50%;background:var(--success);box-shadow:0 0 0 4px color-mix(in srgb,var(--success) 11%,transparent),0 0 14px color-mix(in srgb,var(--success) 68%,transparent);content:""}
    .conversation-stage[data-connection="reconnecting"]>header::after{background:var(--warning);box-shadow:0 0 0 4px color-mix(in srgb,var(--warning) 11%,transparent),0 0 14px color-mix(in srgb,var(--warning) 68%,transparent)}
    .conversation-stage[data-connection="disconnected"]>header::after{background:var(--subtle);box-shadow:0 0 0 4px color-mix(in srgb,var(--subtle) 11%,transparent)}
    .conversation-stage>header h2{font-size:15px!important;letter-spacing:-.025em}.conversation-stage>header .orbit-button{border-radius:10px!important}
    .conversation-stage__field{position:relative;padding:28px 26px!important;background:linear-gradient(90deg,transparent 0,transparent 34px,rgba(255,255,255,.04) 34px,rgba(255,255,255,.04) 35px,transparent 35px)!important;scrollbar-color:var(--border-strong) transparent}
    .conversation-stage__field::before{position:absolute;top:0;bottom:0;left:34px;width:1px;background:linear-gradient(transparent,color-mix(in srgb,var(--signal) 18%,transparent) 12%,color-mix(in srgb,var(--signal) 18%,transparent) 86%,transparent);content:"";pointer-events:none}
    .conversation-stage .message-day-divider{position:relative;z-index:1;margin:1.8rem 0 1.05rem!important;padding-left:24px}.conversation-stage .message-day-divider span{padding:0 8px;border:1px solid var(--border);border-radius:999px;background:var(--surface);color:var(--subtle);font-size:.58rem}
    .conversation-stage .peer-message-group{position:relative;z-index:1;display:flex;align-items:center;gap:.48rem;margin:1.15rem 0 .08rem 8px!important;padding:5px 8px;border-radius:9px;color:var(--foreground);font-size:.72rem;font-weight:800;transition:background 150ms var(--ease-out),color 150ms var(--ease-out)}.conversation-stage .peer-message-group time{color:var(--subtle);font-size:.61rem;font-weight:600}.conversation-stage .peer-message-group:hover{background:var(--signal-soft);color:var(--signal-bright)}
    .conversation-stage .message-row{position:relative;z-index:1;margin-bottom:2px!important}.conversation-stage .message-row>div{transition:border-color 160ms var(--ease-out),box-shadow 160ms var(--ease-out),background 160ms var(--ease-out),transform 160ms var(--ease-out)}.conversation-stage .message-row--incoming>div{max-width:min(46rem,86%)!important;border-color:transparent!important;border-radius:10px!important;background:transparent!important;box-shadow:none!important;padding:.35rem .7rem .5rem 2.65rem!important}.conversation-stage .message-row--incoming:hover>div{background:rgba(255,255,255,.035)!important}.conversation-stage .message-row--incoming.is-group-start>div{padding-top:.55rem!important}.conversation-stage .message-row--outgoing{margin-top:.32rem!important;margin-bottom:.48rem!important}.conversation-stage .message-row--outgoing>div{border-radius:16px 16px 5px 16px!important;background:linear-gradient(135deg,color-mix(in srgb,var(--signal) 96%,#fff 4%),color-mix(in srgb,var(--signal) 72%,#11142b 28%))!important;box-shadow:0 10px 25px rgba(0,0,0,.16)!important}.conversation-stage .message-row--outgoing:hover>div{border-color:var(--border-strong)!important;box-shadow:0 14px 32px rgba(0,0,0,.2)!important}
    .conversation-stage .receipt-trace{padding-top:2px;font-size:.61rem}.conversation-stage .receipt-trace--read{color:#d1ccff}.conversation-stage .message-expiry{font-variant-numeric:tabular-nums}.conversation-stage .message-expiry--near{color:color-mix(in srgb,var(--warning) 88%,#fff 12%);font-weight:700}.conversation-stage .message-expiry--due{color:var(--warning);font-weight:700}
    .conversation-stage .conversation-recovery{display:flex;align-items:center;gap:.52rem;overflow:hidden;border-bottom:1px solid color-mix(in srgb,var(--warning) 30%,transparent);background:color-mix(in srgb,var(--warning) 9%,transparent);padding:.52rem 1.25rem;color:var(--warning);font-size:.7rem;font-weight:700}.conversation-stage .conversation-recovery__dot{width:.4rem;height:.4rem;flex:none;border-radius:50%;background:currentColor;box-shadow:0 0 9px currentColor}
    @media (prefers-reduced-motion:no-preference){.conversation-stage .message-expiry--near{animation:message-expiry-pulse 2.4s ease-in-out infinite}@keyframes message-expiry-pulse{0%,100%{opacity:1}50%{opacity:.58}}}
    .conversation-stage .signal-magnetic-dock{position:relative;margin:12px 16px 16px!important;border-color:color-mix(in srgb,var(--border-strong) 80%,transparent)!important;border-radius:16px!important;background:linear-gradient(180deg,color-mix(in srgb,var(--surface-float) 92%,#0a0b12 8%),color-mix(in srgb,var(--surface) 93%,#0a0b12 7%))!important;box-shadow:0 18px 42px rgba(0,0,0,.3),inset 0 1px 0 rgba(255,255,255,.055)!important}.conversation-stage .signal-magnetic-dock:focus-within{border-color:var(--stage-edge)!important;box-shadow:0 0 0 3px color-mix(in srgb,var(--signal) 14%,transparent),0 18px 42px rgba(0,0,0,.3)!important}.conversation-stage .signal-magnetic-dock>button:last-child{border-radius:11px!important}
    .conversation-stage .transfer-current{margin-left:10px;border-radius:12px!important}.conversation-stage .peer-context{top:4.5rem!important;right:1rem!important;border-radius:14px!important;background:color-mix(in srgb,var(--surface-raised) 97%,#05060b 3%)!important}.conversation-stage .peer-context__head{background:rgba(255,255,255,.018)}.conversation-stage [role="status"]{letter-spacing:.005em}
    .conversation-stage>header .orbit-button::after{position:absolute;right:0;bottom:calc(100% + 8px);padding:5px 7px;border:1px solid var(--border-strong);border-radius:6px;background:var(--surface-raised);box-shadow:0 8px 22px rgba(0,0,0,.22);color:var(--foreground);content:attr(aria-label);font-size:.61rem;font-weight:700;letter-spacing:.01em;opacity:0;pointer-events:none;transform:translateY(3px);transition:opacity 130ms var(--ease-out),transform 130ms var(--ease-out);white-space:nowrap}.conversation-stage>header .orbit-button:hover::after,.conversation-stage>header .orbit-button:focus-visible::after{opacity:1;transform:translateY(0)}
    @media(max-width:767px){.conversation-stage{min-height:calc(100svh - 5rem)!important;border-radius:0!important;border-inline:0!important}.conversation-stage>header{min-height:62px;padding-inline:14px!important}.conversation-stage__field{padding:20px 14px 14px!important;background:linear-gradient(90deg,transparent 0,transparent 18px,rgba(255,255,255,.035) 18px,rgba(255,255,255,.035) 19px,transparent 19px)!important}.conversation-stage__field::before{left:18px}.conversation-stage .message-day-divider{padding-left:10px}.conversation-stage .peer-message-group{margin-left:3px!important}.conversation-stage article>div{max-width:90%!important}.conversation-stage .signal-magnetic-dock{margin:8px 10px 10px!important}.conversation-stage .peer-context{position:fixed;z-index:60;top:auto!important;right:0!important;bottom:0!important;left:0!important;width:auto!important;border-right:0;border-bottom:0;border-left:0;border-radius:18px 18px 0 0!important}}
  `}</style>;
}
