import React from "react";

export function WorkspaceConsoleStyles() {
  return <style>{`
    /* Complete workspace redesign: editorial chrome + command density + original live chat behavior. */
    .workspace-console{--console-red:#e54255;--console-red-hot:#ff7683;--console-red-wash:rgba(229,66,85,.12);--console-edge:rgba(255,255,255,.13);--console-hairline:rgba(255,255,255,.085);--console-surface:#0b0b0c;--console-raised:#111113;--console-text:#f5f5f7;--console-muted:#949499;--console-subtle:#626266;position:relative;isolation:isolate;min-height:100vh;background:radial-gradient(circle at 88% 8%,rgba(221,38,60,.14),transparent 25%),radial-gradient(circle at 10% 94%,rgba(151,25,41,.09),transparent 27%),#050505!important}
    .workspace-console::before{position:fixed;z-index:-1;top:15vh;right:-20rem;width:43rem;height:43rem;border:1px solid rgba(255,102,116,.11);border-radius:50%;box-shadow:0 0 0 50px rgba(255,72,92,.018),0 0 0 100px rgba(255,72,92,.012);content:"";pointer-events:none}
    .workspace-console__page{width:min(100% - 28px,1400px)!important;padding:20px 0!important}
    .workspace-console__navbar{min-height:58px!important;border-color:rgba(255,255,255,.16)!important;border-radius:18px!important;background:rgba(8,8,9,.88)!important;box-shadow:0 14px 48px rgba(0,0,0,.34)!important;backdrop-filter:blur(20px)!important}
    .workspace-console__navbar::before{display:block;width:32px;height:1px;background:var(--console-red-hot);box-shadow:16px 0 24px rgba(229,66,85,.62);content:"";opacity:.94}
    .workspace-console__brand{gap:9px!important;color:var(--console-text)!important;font-size:13px!important;letter-spacing:.035em!important}
    .workspace-console__brand-mark{width:26px!important;height:26px!important;border-color:rgba(255,118,131,.5)!important;border-radius:6px!important;background:#170d0f!important;color:var(--console-red-hot)!important}
    .workspace-console__status{color:var(--console-muted)!important;font-family:ui-monospace,SFMono-Regular,Menlo,monospace!important;font-size:10px!important;font-weight:700!important;letter-spacing:.045em!important;text-transform:uppercase!important}
    .workspace-console__status i{background:var(--console-red-hot)!important;box-shadow:0 0 16px rgba(255,118,131,.7)!important}
    .workspace-console__navbar .signal-status{border-color:var(--console-hairline)!important;border-radius:6px!important;background:rgba(255,255,255,.025)!important;color:var(--console-muted)!important;font-family:ui-monospace,SFMono-Regular,Menlo,monospace!important;font-size:10px!important}
    .workspace-console__identity{border-color:rgba(255,255,255,.22)!important;border-radius:7px!important;background:var(--console-text)!important;padding:8px 11px!important;color:#090909!important;font-size:11px!important;letter-spacing:-.01em!important}
    .workspace-console__frame{position:relative;height:max(640px,calc(100dvh - 116px))!important;min-height:0!important;margin-top:18px!important;border-color:rgba(255,255,255,.12)!important;border-radius:24px!important;overflow:hidden!important;background:#080809!important;box-shadow:0 28px 80px rgba(0,0,0,.42)!important}.workspace-console__frame>.relay-stream,.workspace-console__frame>.private-field{height:100%!important;min-height:0!important}
    .workspace-console .signal-orbit{background:linear-gradient(180deg,rgba(15,15,16,.96) 0%,rgba(8,8,9,.98) 100%)!important}
    .workspace-console .signal-orbit::after{position:absolute;top:0;right:0;bottom:0;width:1px;background:linear-gradient(transparent,var(--console-red-wash) 20%,var(--console-red-wash) 80%,transparent);content:""}
    .workspace-console .signal-orbit__thread{background:linear-gradient(transparent,rgba(255,118,131,.32) 22%,rgba(255,118,131,.32) 78%,transparent)!important}
    .workspace-console .signal-orbit .orbit-button{border-radius:9px!important;color:#7c7c81!important}
    .workspace-console .signal-orbit .orbit-button:hover{border-color:var(--console-hairline)!important;background:rgba(255,255,255,.045)!important;color:var(--console-text)!important}
    .workspace-console .signal-orbit .orbit-button[data-active="true"]{border-color:rgba(255,118,131,.42)!important;background:linear-gradient(135deg,rgba(229,66,85,.18),rgba(229,66,85,.055))!important;color:var(--console-red-hot)!important;box-shadow:inset 2px 0 0 var(--console-red),0 0 22px rgba(229,66,85,.09)!important}
    .workspace-console .relay-stream{background:linear-gradient(180deg,rgba(13,13,14,.94),rgba(7,7,8,.98))!important}
    .workspace-console .chat-index__header{position:relative;padding:22px 18px 17px!important;border-bottom:1px solid var(--console-hairline)}
    .workspace-console .chat-index__header::after{position:absolute;right:18px;bottom:-1px;left:18px;height:1px;background:linear-gradient(90deg,var(--console-red),rgba(229,66,85,0));content:"";opacity:.72}
    .workspace-console .chat-index__eyebrow,.workspace-console .conversation-stage__eyebrow{color:var(--console-red-hot)!important;font-size:9px!important;letter-spacing:.14em!important}
    .workspace-console .chat-index__header h1{margin-top:7px!important;color:var(--console-text)!important;font-size:18px!important;font-weight:650!important;letter-spacing:-.055em!important}
    .workspace-console .chat-index__header p:not(.chat-index__eyebrow){color:var(--console-muted)!important;font-size:11px!important}
    .workspace-console .chat-index__new{min-height:31px!important;border-color:#f6f6f7!important;border-radius:7px!important;background:#f6f6f7!important;padding:0 9px!important;color:#090909!important;font-family:ui-monospace,SFMono-Regular,Menlo,monospace!important;font-size:10px!important;letter-spacing:.015em!important;box-shadow:none!important}
    .workspace-console .chat-index__filter{margin:14px 14px 8px!important;border-color:var(--console-hairline)!important;border-radius:7px!important;background:#070708!important;padding:9px 10px!important;color:#77777c!important}
    .workspace-console .chat-index__filter:focus-within{border-color:rgba(255,118,131,.62)!important;box-shadow:0 0 0 3px rgba(229,66,85,.11)!important}
    .workspace-console .chat-index__filter input{color:var(--console-text)!important;font-size:11px!important}
    .workspace-console .chat-index__list{padding:4px 8px 16px!important}
    .workspace-console .chat-index__list-label{padding:12px 8px 7px!important;color:#69696d!important;font-size:9px!important}
    .workspace-console .chat-index__item{gap:10px!important;margin:2px 0!important;border-radius:7px!important;padding:9px 8px!important}
    .workspace-console .chat-index__item:hover{border-color:rgba(255,255,255,.08)!important;background:rgba(255,255,255,.038)!important}
    .workspace-console .chat-index__item.is-active{border-color:rgba(255,118,131,.23)!important;background:linear-gradient(90deg,rgba(229,66,85,.16),rgba(229,66,85,.035) 76%,transparent)!important;box-shadow:inset 2px 0 0 var(--console-red)!important}
    .workspace-console .chat-index__item.is-protected{background-color:rgba(229,66,85,.055)!important}
    .workspace-console .chat-index__item-head>span{color:var(--console-text)!important;font-size:12px!important;font-weight:700!important}.workspace-console .chat-index__item-head time{color:#78787d!important;font-family:ui-monospace,SFMono-Regular,Menlo,monospace!important;font-size:9px!important}.workspace-console .chat-index__item-state{color:#929297!important;font-size:10px!important}.workspace-console .chat-index__item.is-protected .chat-index__item-state{color:var(--console-red-hot)!important}.workspace-console .chat-index__selected{width:4px!important;height:4px!important}.workspace-console .chat-index__item.is-active .chat-index__selected{background:var(--console-red-hot)!important;box-shadow:0 0 12px var(--console-red-hot)!important}
    .workspace-console .chat-index__empty{min-height:21rem!important;padding:20px 18px!important}.workspace-console .chat-index__empty>span{border:1px solid rgba(255,118,131,.3)!important;border-radius:7px!important;background:rgba(229,66,85,.09)!important;color:var(--console-red-hot)!important}.workspace-console .chat-index__empty h2{color:var(--console-text)!important;font-size:15px!important;letter-spacing:-.04em!important}.workspace-console .chat-index__empty p{color:var(--console-muted)!important;font-size:11px!important}.workspace-console .chat-index__empty button{color:var(--console-red-hot)!important;font-family:ui-monospace,SFMono-Regular,Menlo,monospace!important;font-size:10px!important}
    .workspace-console .chat-index__account{border-top-color:var(--console-hairline)!important}.workspace-console .chat-index__account b{color:var(--console-text)!important}.workspace-console .chat-index__account small,.workspace-console .chat-index__secure{color:var(--console-muted)!important}
    .workspace-console .chat-workspace{min-height:0!important;background:radial-gradient(circle at 95% 6%,rgba(221,38,60,.08),transparent 24%),#080809!important}
    .workspace-console .workspace-privacy-checkup{border-color:rgba(255,118,131,.26)!important;border-radius:9px!important;background:linear-gradient(100deg,rgba(229,66,85,.13),rgba(229,66,85,.035))!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.035)!important}.workspace-console .workspace-privacy-checkup>span:first-child{border-radius:7px!important;background:var(--console-red)!important}.workspace-console .workspace-privacy-checkup .text-sm{color:var(--console-text)!important}.workspace-console .workspace-privacy-checkup .text-xs{color:#a8a8ae!important}.workspace-console .workspace-privacy-checkup svg:last-child{color:var(--console-red-hot)!important}
    .workspace-console .conversation-stage{--stage-edge:rgba(255,118,131,.48);--stage-grid:rgba(255,255,255,.014);min-height:0!important;border-color:rgba(255,255,255,.15)!important;border-radius:18px!important;background:#0d0d0e!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.045),0 20px 58px rgba(0,0,0,.2)!important}
    .workspace-console .conversation-stage::before{background-image:linear-gradient(var(--stage-grid) 1px,transparent 1px),linear-gradient(90deg,var(--stage-grid) 1px,transparent 1px)!important;background-size:42px 42px!important;mask-image:linear-gradient(to bottom,black,transparent 42%)!important}
    .workspace-console .conversation-stage>header{min-height:67px!important;border-bottom-color:var(--console-hairline)!important;background:rgba(255,255,255,.018)!important}
    .workspace-console .conversation-stage>header::after{background:var(--console-red-hot)!important;box-shadow:0 0 0 4px rgba(255,118,131,.1),0 0 14px rgba(255,118,131,.55)!important}
    .workspace-console .conversation-stage[data-connection="reconnecting"]>header::after{background:var(--warning)!important}.workspace-console .conversation-stage[data-connection="disconnected"]>header::after{background:#77777b!important;box-shadow:none!important}
    .workspace-console .conversation-stage>header h2{color:var(--console-text)!important;font-size:14px!important}.workspace-console .conversation-stage__state{color:#a0a0a5!important;font-family:ui-monospace,SFMono-Regular,Menlo,monospace!important;font-size:9px!important}.workspace-console .conversation-stage__state i{background:var(--console-red-hot)!important;box-shadow:0 0 0 3px rgba(255,118,131,.08)!important}.workspace-console .conversation-stage__state i[data-state="reconnecting"]{background:var(--warning)!important}.workspace-console .conversation-stage__state i[data-state="disconnected"]{background:#747478!important}
    .workspace-console .conversation-stage>header .orbit-button{border-color:transparent!important;border-radius:7px!important;color:#8e8e94!important}.workspace-console .conversation-stage>header .orbit-button:hover,.workspace-console .conversation-stage>header .orbit-button:focus-visible{border-color:var(--console-hairline)!important;background:rgba(255,255,255,.045)!important;color:var(--console-text)!important}.workspace-console .conversation-stage>header .orbit-button[aria-pressed="true"]{border-color:rgba(255,118,131,.35)!important;background:var(--console-red-wash)!important;color:var(--console-red-hot)!important}
    .workspace-console .conversation-command-menu summary{border-color:transparent!important;border-radius:7px!important;color:#8e8e94!important}.workspace-console .conversation-command-menu[open] summary{border-color:var(--console-hairline)!important;background:rgba(255,255,255,.045)!important;color:var(--console-text)!important}.workspace-console .conversation-command-menu>div{border:1px solid var(--console-edge)!important;border-radius:9px!important;background:#141416!important;box-shadow:0 22px 64px rgba(0,0,0,.46)!important}.workspace-console .conversation-command-menu button{font-size:11px!important}.workspace-console .conversation-command-menu button:hover{background:rgba(255,255,255,.05)!important}
    .workspace-console .conversation-policy-strip{border-bottom-color:var(--console-hairline)!important;background:#101011!important;padding:10px 20px!important}.workspace-console .conversation-policy-strip p{color:#7d7d82!important;font-family:ui-monospace,SFMono-Regular,Menlo,monospace!important;font-size:8px!important;letter-spacing:.12em!important}.workspace-console .conversation-policy-strip button{border-color:rgba(255,255,255,.105)!important;border-radius:5px!important;color:#a2a2a7!important;font-family:ui-monospace,SFMono-Regular,Menlo,monospace!important;font-size:9px!important}.workspace-console .conversation-policy-strip button[class*="border-[var(--signal)]"]{border-color:rgba(255,118,131,.58)!important;background:rgba(229,66,85,.13)!important;color:var(--console-red-hot)!important}.workspace-console .conversation-policy-strip summary{border-color:var(--console-hairline)!important;border-radius:6px!important;color:#a2a2a7!important;font-size:10px!important}
    .workspace-console .line-policy-capsule{display:flex;align-items:flex-end;gap:18px}.workspace-console .line-policy-capsule>div:first-child>span{display:block;margin-top:3px;color:#d7d7da;font-size:11px;letter-spacing:-.012em}.workspace-console .line-policy-capsule>div:last-child{margin-top:0!important}.workspace-console .conversation-policy-strip details[open] summary{border-color:rgba(255,118,131,.5)!important;background:rgba(229,66,85,.08)!important;color:var(--console-text)!important}
    .workspace-console .archive-lens{border-bottom-color:rgba(255,118,131,.2)!important;background:linear-gradient(90deg,rgba(229,66,85,.13),rgba(229,66,85,.035))!important}.workspace-console .archive-lens label{border-color:var(--console-hairline)!important;border-radius:7px!important;background:#0c0c0d!important}.workspace-console .archive-lens input{color:var(--console-text)!important}.workspace-console .archive-lens button{border-color:var(--console-hairline)!important;border-radius:6px!important}
    .workspace-console .conversation-stage__field{padding:24px 28px!important;background:transparent!important}.workspace-console .conversation-stage__field::before{left:29px!important;background:linear-gradient(transparent,rgba(255,118,131,.22) 14%,rgba(255,118,131,.08) 88%,transparent)!important}
    .workspace-console .message-day-divider{margin:1.65rem 0 1rem!important;padding-left:22px!important}.workspace-console .message-day-divider::before,.workspace-console .message-day-divider::after{background:var(--console-hairline)!important}.workspace-console .message-day-divider span{border-color:var(--console-hairline)!important;border-radius:4px!important;background:#101011!important;color:#838388!important;font-family:ui-monospace,SFMono-Regular,Menlo,monospace!important;font-size:8px!important;letter-spacing:.065em!important}
    .workspace-console .peer-message-group{margin:1.25rem 0 .2rem 7px!important;border-radius:6px!important;color:var(--console-text)!important;font-family:ui-monospace,SFMono-Regular,Menlo,monospace!important;font-size:10px!important}.workspace-console .peer-message-group time{color:#717176!important;font-size:9px!important}.workspace-console .peer-message-group:hover{background:rgba(229,66,85,.09)!important;color:var(--console-red-hot)!important}
    .workspace-console .message-row{display:flex!important;width:100%!important}.workspace-console .message-row--incoming{justify-content:flex-start!important}.workspace-console .message-row--outgoing{justify-content:flex-end!important;margin-top:.38rem!important;margin-bottom:.48rem!important}.workspace-console .message-row>div{width:fit-content!important;min-width:0}.workspace-console .message-row--incoming>div{max-width:min(49rem,86%)!important;border-radius:7px!important;padding:.33rem .8rem .55rem 2.55rem!important;color:#e7e7e9!important}.workspace-console .message-row--incoming:hover>div{background:rgba(255,255,255,.035)!important}.workspace-console .message-row--outgoing>div{border-color:rgba(183,169,255,.34)!important;border-radius:13px 13px 5px 13px!important;background:linear-gradient(140deg,rgba(118,99,224,.96),rgba(79,61,176,.94))!important;box-shadow:0 11px 27px rgba(0,0,0,.2)!important}.workspace-console .message-row--outgoing:hover>div{border-color:rgba(221,214,255,.65)!important}.workspace-console .message-row p{letter-spacing:-.004em}.workspace-console .receipt-trace{font-family:ui-monospace,SFMono-Regular,Menlo,monospace!important;font-size:9px!important}.workspace-console .receipt-trace--read{color:#e7e3ff!important}.workspace-console .message-expiry--near{color:#ffd08d!important}.workspace-console .typing-current{border-color:rgba(255,118,131,.34)!important;border-radius:7px!important;background:rgba(229,66,85,.1)!important;color:var(--console-red-hot)!important;font-family:ui-monospace,SFMono-Regular,Menlo,monospace!important;font-size:10px!important}
    .workspace-console .message-action-shelf{display:inline-flex;gap:3px;margin-left:2px;opacity:0;transform:translateY(1px);transition:opacity 150ms var(--ease-out,linear),transform 150ms var(--ease-out,linear)}.workspace-console .message-row:hover .message-action-shelf,.workspace-console .message-row:focus-within .message-action-shelf{opacity:1;transform:translateY(0)}.workspace-console .message-action-shelf button{display:inline-flex;align-items:center;gap:3px;border:1px solid rgba(255,255,255,.2);border-radius:4px;background:rgba(10,8,24,.16);padding:2px 4px;color:inherit;font-size:8px;font-weight:700;line-height:1}.workspace-console .message-action-shelf button:hover,.workspace-console .message-action-shelf button:focus-visible{background:rgba(255,255,255,.18);color:#fff}.workspace-console .message-action-shelf button:last-child:hover,.workspace-console .message-action-shelf button:last-child:focus-visible{border-color:rgba(255,197,205,.66);background:rgba(127,22,36,.27)}
    .workspace-console .message-field-empty{background:radial-gradient(circle at 50% 38%,rgba(229,66,85,.075),transparent 32%)}.workspace-console .message-field-empty .signal-signature,.workspace-console .message-field-empty__mark{border-color:rgba(255,118,131,.3)!important;border-radius:7px!important;background:rgba(229,66,85,.085)!important;color:var(--console-red-hot)!important}.workspace-console .message-field-empty>p{color:var(--console-red-hot)!important;font-family:ui-monospace,SFMono-Regular,Menlo,monospace!important;font-size:9px!important}.workspace-console .message-field-empty h3{color:var(--console-text)!important;font-size:18px!important}.workspace-console .message-field-empty>div{color:var(--console-muted)!important;font-size:11px!important}
    .workspace-console .conversation-recovery{border-bottom-color:rgba(243,179,107,.28)!important;background:rgba(243,179,107,.075)!important;font-family:ui-monospace,SFMono-Regular,Menlo,monospace!important;font-size:10px!important}
    .workspace-console .message-rail-transfer{border-color:rgba(255,118,131,.22)!important;border-radius:7px!important;background:#101011!important}.workspace-console .transfer-current__bar{background:linear-gradient(90deg,var(--console-red),#9e8cff,#6de0bc)!important}
    .workspace-console .message-rail{margin:12px 16px 16px!important;border-color:var(--console-edge)!important;border-radius:9px!important;background:linear-gradient(180deg,#131315,#0d0d0e)!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.04),0 18px 44px rgba(0,0,0,.27)!important}.workspace-console .message-rail:focus-within{border-color:rgba(255,118,131,.55)!important;box-shadow:0 0 0 3px rgba(229,66,85,.09),0 18px 44px rgba(0,0,0,.27)!important}.workspace-console .conversation-composer__rail{margin:0 .42rem .52rem!important;color:#79797d!important;font-size:9px!important}.workspace-console .conversation-composer__rail span:last-child{color:var(--console-red-hot)!important}.workspace-console .conversation-composer__input label{border-color:var(--console-hairline)!important;border-radius:7px!important;color:#99999e!important}.workspace-console .conversation-composer__input label:hover{border-color:rgba(255,118,131,.48)!important;color:var(--console-red-hot)!important}.workspace-console .conversation-composer__input input{color:var(--console-text)!important;font-size:12px!important}.workspace-console .conversation-composer__input button[type="submit"]{border-radius:7px!important;background:#f5f5f7!important;color:#090909!important;box-shadow:none!important}.workspace-console .conversation-composer__input button[type="submit"]:disabled{background:rgba(255,255,255,.18)!important;color:#747478!important}.workspace-console .conversation-composer__meta{border-top-color:var(--console-hairline)!important;color:#76767a!important;font-family:ui-monospace,SFMono-Regular,Menlo,monospace!important;font-size:8px!important}
    .workspace-console .message-rail[data-state="draft"]{border-color:rgba(255,118,131,.33)!important}.workspace-console .message-rail[data-state="uploading"] .composer-rail__state{color:#b7a9ff!important}.workspace-console .message-rail[data-state="failed"]{border-color:rgba(255,150,155,.54)!important}.workspace-console .message-rail[data-state="failed"] .composer-rail__state{color:#ffb4bd!important}.workspace-console .message-rail[data-state="reconnecting"],.workspace-console .message-rail[data-state="disconnected"]{border-color:rgba(243,179,107,.38)!important}.workspace-console .composer-rail__state{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
    .workspace-console .peer-context{border-color:var(--console-edge)!important;border-radius:10px!important;background:linear-gradient(150deg,#171719,#0c0c0d)!important;box-shadow:0 26px 74px rgba(0,0,0,.55)!important}.workspace-console .peer-context__head{border-bottom-color:var(--console-hairline)!important;background:rgba(255,255,255,.016)!important;color:var(--console-red-hot)!important;font-family:ui-monospace,SFMono-Regular,Menlo,monospace!important;font-size:9px!important}.workspace-console .peer-context__head button{border-color:var(--console-hairline)!important;border-radius:6px!important}.workspace-console .peer-context__identity h3,.workspace-console .peer-context__fact b{color:var(--console-text)!important}.workspace-console .peer-context__identity p,.workspace-console .peer-context__fact{color:var(--console-muted)!important}.workspace-console .peer-context__fact{border-color:var(--console-hairline)!important}.workspace-console .peer-context__actions button{font-size:11px!important}.workspace-console .peer-context__actions button:hover{background:rgba(255,255,255,.045)!important}.workspace-console .peer-context__note{border-top-color:var(--console-hairline)!important;color:#828287!important;font-size:10px!important}
    .workspace-console .direct-stage{border-color:var(--console-edge)!important;background:radial-gradient(circle at 88% 14%,rgba(229,66,85,.11),transparent 29%),linear-gradient(145deg,#121213,#090909 68%)!important}.workspace-console .direct-stage__intro>p{color:var(--console-red-hot)!important;font-family:ui-monospace,SFMono-Regular,Menlo,monospace!important;font-size:10px!important}.workspace-console .direct-stage__intro h2{color:var(--console-text)!important}.workspace-console .direct-stage__intro>div{color:var(--console-muted)!important}.workspace-console .direct-stage__command{border-bottom-color:var(--console-hairline)!important}.workspace-console .direct-stage__command label{border-color:var(--console-edge)!important;background:#09090a!important}.workspace-console .direct-stage__command label:focus-within{border-color:rgba(255,118,131,.65)!important;box-shadow:0 0 0 3px rgba(229,66,85,.1)!important}.workspace-console .direct-stage__command button{border-color:#f6f6f7!important;background:#f6f6f7!important;color:#090909!important}.workspace-console .direct-stage__facts{color:#96969b!important;font-family:ui-monospace,SFMono-Regular,Menlo,monospace!important;font-size:10px!important}.workspace-console .direct-stage__facts span:first-child{color:var(--console-red-hot)!important}
    .workspace-console .direct-stage--pending{background:radial-gradient(circle at 12% 86%,rgba(183,169,255,.1),transparent 28%),radial-gradient(circle at 88% 14%,rgba(229,66,85,.11),transparent 29%),linear-gradient(145deg,#121213,#090909 68%)!important}.workspace-console .direct-stage__pending-card{display:flex;align-items:flex-start;gap:10px;margin-top:18px;border:1px solid rgba(255,118,131,.22);border-radius:9px;background:rgba(229,66,85,.055);padding:12px}.workspace-console .direct-stage__pending-card>span{display:grid;place-items:center;flex:0 0 auto;width:26px;height:26px;border:1px solid rgba(255,118,131,.34);border-radius:6px;color:var(--console-red-hot)}.workspace-console .direct-stage__pending-card b{display:block;color:var(--console-text);font-size:12px}.workspace-console .direct-stage__pending-card p{margin-top:2px;color:var(--console-muted);font-size:11px;line-height:1.45}.workspace-console .direct-stage__secondary{margin-top:12px;border:1px solid var(--console-edge);border-radius:6px;padding:8px 10px;color:#d3d3d6;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:10px;font-weight:700}.workspace-console .direct-stage__secondary:hover,.workspace-console .direct-stage__secondary:focus-visible{border-color:rgba(255,118,131,.5);color:var(--console-red-hot)}.workspace-console .chat-index__requests{margin:0 10px 9px;border:1px solid var(--console-hairline);border-radius:10px;background:rgba(255,255,255,.018);overflow:hidden}.workspace-console .chat-index__requests-label{display:flex;align-items:center;justify-content:space-between;padding:8px 10px 6px;color:#7f7f84;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:8px;font-weight:800;letter-spacing:.13em}.workspace-console .chat-index__requests-label b{color:var(--console-red-hot)}.workspace-console .chat-index__request{display:grid;grid-template-columns:auto minmax(0,1fr);gap:8px;padding:9px 10px;border-top:1px solid var(--console-hairline)}.workspace-console .chat-index__request>div:nth-child(2){min-width:0}.workspace-console .chat-index__request b{display:block;overflow:hidden;color:var(--console-text);font-size:11px;text-overflow:ellipsis;white-space:nowrap}.workspace-console .chat-index__request span{display:block;margin-top:2px;color:#87878c;font-size:9px}.workspace-console .chat-index__request-actions{grid-column:2;display:flex;gap:4px}.workspace-console .chat-index__request-actions button{border:1px solid var(--console-hairline);border-radius:5px;padding:4px 6px;color:#b9b9bd;font-size:9px;font-weight:700}.workspace-console .chat-index__request-actions button:first-child{border-color:rgba(255,118,131,.42);background:rgba(229,66,85,.12);color:var(--console-red-hot)}.workspace-console .chat-index__request-actions button:last-child{color:#d69299}.workspace-console .chat-index__request-actions button:disabled{cursor:not-allowed;opacity:.5}
    @media(min-width:768px){.workspace-console__frame{grid-template-columns:76px minmax(310px,352px) minmax(0,1fr)!important}.workspace-console .chat-workspace{padding:0!important}.workspace-console .private-field>div.relative{min-height:0!important;padding:18px 20px 20px!important}.workspace-console .conversation-stage{height:100%!important;min-height:0!important}}
    @media(max-width:767px){.workspace-console__page{width:100%!important;padding:0!important}.workspace-console::before{top:auto;right:-13rem;bottom:6rem;width:28rem;height:28rem}.workspace-console__navbar{display:none!important}.workspace-console__frame{min-height:100svh!important;margin:0!important;border:0!important;border-radius:0!important;background:radial-gradient(circle at 92% 8%,rgba(221,38,60,.1),transparent 28%),#080809!important}.workspace-console .signal-orbit{background:rgba(12,12,13,.95)!important}.workspace-console .chat-workspace{background:radial-gradient(circle at 90% 6%,rgba(221,38,60,.09),transparent 25%),#080809!important}.workspace-console .workspace-privacy-checkup{margin-inline:10px!important;width:calc(100% - 20px)!important}.workspace-console .conversation-stage{border:0!important;border-radius:0!important;background:radial-gradient(circle at 96% 3%,rgba(221,38,60,.06),transparent 20%),#09090a!important}.workspace-console .conversation-stage__field{padding:18px 14px 12px!important;background:linear-gradient(90deg,transparent 0,transparent 17px,rgba(255,118,131,.09) 17px,rgba(255,118,131,.09) 18px,transparent 18px)!important}.workspace-console .conversation-stage__field::before{left:17px!important}.workspace-console .message-day-divider{padding-left:9px!important}.workspace-console .message-row--incoming>div{padding-left:1.65rem!important}.workspace-console .message-action-shelf{opacity:1;transform:none}.workspace-console .message-action-shelf button span{display:none}.workspace-console .line-policy-capsule{align-items:flex-start;gap:9px;flex-direction:column}.workspace-console .message-rail{margin:8px 10px 10px!important}.workspace-console .conversation-composer__meta{gap:.35rem!important}.workspace-console .peer-context{border-radius:14px 14px 0 0!important}.workspace-console .chat-workspace__mobile-head{border-bottom-color:var(--console-hairline)!important;background:#0d0d0e!important}.workspace-console .chat-workspace__mobile-head p{color:var(--console-red-hot)!important;font-family:ui-monospace,SFMono-Regular,Menlo,monospace!important}}
    @media(prefers-reduced-motion:reduce){.workspace-console *, .workspace-console *::before,.workspace-console *::after{animation:none!important;transition-duration:.01ms!important}}
  `}</style>;
}
